Panel event management : group coorganization
lafranceinsoumise/actionpopulaire.fr pull request #1088
Opened 2021-09-21 16:12 UTC by maxGoaz

2021-09-27 15:07 UTC, maxGoaz commented
- Design of panel event organization : https://www.figma.com/file/hjHk8qFdJly8bmbIgu0IHG/ACTION-POPULAIRE-SOURCE?node-id=2693%3A32484
- New emails `EVENT_GROUP_COORGANIZATION_INVITE` and `EVENT_GROUP_COORGANIZATION_ACCEPTED`

_Database_
- Get pending invitations by `Activity.TYPE_GROUP_COORGANIZATION_INVITE`
- When invitation accepted, replace pending inivtations by `Activity.TYPE_GROUP_COORGANIZATION_ACCEPTED`

2021-09-28 13:08 UTC, giuseppedeponte requested changes

2021-09-28 13:08 UTC, giuseppedeponte commented on agir/events/views/event_views.py
> +            return HttpResponseRedirect(reverse("dashboard"))
Pour vérifier si la personne est connectée :
```suggestion
        if not self.request.user.is_authenticated or self.request.user.person is None:
            return HttpResponseRedirect(reverse("dashboard"))
```
Il peut y avoir des utilisateurs connectés qui ne sont pas des personnes (:alien: , :robot:,...)

2021-09-28 13:08 UTC, giuseppedeponte commented on agir/events/views/event_views.py
> +class ConfirmEventGroupCoorganization(View):
Si tu veux il existe une `RedirectView` dans Django : https://docs.djangoproject.com/fr/3.2/ref/class-based-views/base/#redirectview pour laquelle tu peux juste surcharger la methode `get_redirect_url`

2021-09-28 13:15 UTC, maxGoaz commented on agir/events/components/EventSettings/EventOrganization.js
> +    mutate(api.getEventEndpoint("getDetailAdvanced", { eventPk }));
Pour pouvoir afficher les groupes invités _en attente_

2021-09-28 13:37 UTC, maxGoaz commented on agir/events/tasks.py
> +        "DATE": now(),
Dans l'email ça me donne par exemple : **28 septembre 2021 14:39** , est-ce que l'on veut un autre format ?

2021-09-28 14:36 UTC, maxGoaz commented on agir/events/views/event_views.py
> +            return HttpResponseRedirect(reverse("dashboard"))
En réalité ce cas arrive vraiment ? Je pensais que le fait d'être authentifié suffisait

2021-09-28 14:42 UTC, maxGoaz commented on agir/events/components/EventSettings/EventSettings.js
> +    endTime: PropTypes.oneOf(PropTypes.string, PropTypes.object),
En effet je crois pas, il y avait un warning il me semble

2021-09-28 14:42 UTC, giuseppedeponte commented on agir/events/views/event_views.py
> +            return HttpResponseRedirect(reverse("dashboard"))
Oui, je crois que ça peut arriver : en tout cas c'est comme ça qu'on vérifie partout dans le code

2021-09-29 13:14 UTC, jillro approved these changes

2021-09-29 13:14 UTC, jillro commented on agir/gestion/migrations/0005_auto_20210928_1654.py
> +# Generated by Django 3.1.13 on 2021-09-28 14:54
Elle devrait pas être là cette migration ?

2021-09-29 13:14 UTC, jillro commented on agir/mailing/migrations/0040_auto_20210928_1654.py
> +# Generated by Django 3.1.13 on 2021-09-28 14:54
Elle non plus.

2021-09-29 13:14 UTC, jillro commented on agir/events/urls.py
> +        "evenements/<uuid:pk>/confirm-group-coorganization/",
soit on est en anglais sur les URL de l'API soit on est en français mais je crois qu'en est plus sur français pour le moment !

2021-09-29 13:14 UTC, jillro commented on agir/events/models.py
> +        "people.Person",
Diff inutile non ?

2021-09-29 13:15 UTC, jillro requested changes
Points importants :
* migrations inutiles à enlever
* nommage des champs du nouveau modèle

2021-09-29 14:04 UTC, maxGoaz commented on agir/gestion/migrations/0005_auto_20210928_1654.py
> +# Generated by Django 3.1.13 on 2021-09-28 14:54
En effet les migrations de `gestion` et `mailiing` ont été créées depuis ce que j'ai récupéré sur staging, @aktiur m'a dit que c'était ok de les ajouter mais peut-être que c'est mieux de les retirer ?

2021-09-29 14:14 UTC, maxGoaz commented on agir/activity/components/ActivityPage/ActivityCard/GenericCard.js
> +          {Individual || "Quelqu'un"} a proposé à {SupportGroup} de co-organiser{" "}
C'était un refactor pour regrouper les 
`case "group-coorganization-invite": `
et 
`case "group-coorganization-accepted":`
ensemble

2021-09-29 17:01 UTC, maxGoaz commented on agir/events/serializers.py
> +        groups_invited = SupportGroup.objects.filter(
Je suis pas sûr d'avoir compris. Ici je récupère les différents groupes invités `en attente` par rapport à l'événement. Avec un serializer d'invitation je ne pourrai pas les récupérer plus facilement ?

J'ai quand même ajouté un `related_name` pour accéder aux invitations depuis les événéments, mais je suppose que cela alourdi les requêtes des événements et allège celle des invitations liées aux événéments. Or il y en a peu d'invitations et de requêtes d'invitation par rapport aux événements.

2021-09-29 17:02 UTC, maxGoaz commented on agir/events/models.py
> +        "people.Person",
C'était un refactor de lisibilité, mais c'est personnel je peux l'enlever !

2021-09-30 09:28 UTC, jillro commented on agir/gestion/migrations/0005_auto_20210928_1654.py
> +# Generated by Django 3.1.13 on 2021-09-28 14:54
Si elles doivent être ajoutées ce serait bien de le faire directement dans staging avec une PR adaptée, ça éviterait des risques de conflit.

2021-09-30 09:42 UTC, jillro commented on agir/events/serializers.py
> +        groups_invited = SupportGroup.objects.filter(
Le related_name n'alourdi en rien, si tu le mets pas il y en a un de toute façon par défaut. Un truc comme ça serait pas plus simple ? C'est une requête en moins.

```python
invited_groups = SupportGroup.objects.filter(invitations__status=Invitation.INVITATION_PENDING)
```

2021-09-30 09:43 UTC, jillro commented on agir/events/models.py
> +    person_respond = models.ForeignKey(
response toujours

2021-09-30 09:44 UTC, jillro commented on agir/events/models.py
> +        related_name="group_coorganization_invitations",
je pense que "invitations" pour le related name serait mieux, parce que le modèle va peut-être être plus large que ça

sinon en cohérence il faudrait aussi appeler le modèle "GroupCoorganizationInvitation"

2021-09-30 09:44 UTC, jillro commented on agir/events/models.py
> +        related_name="person_respond",
du coup du point de vue de la personne, c'est pas une "person_respond", c'est une "invitation_response"

2021-09-30 09:48 UTC, maxGoaz commented on agir/events/models.py
> +    person_respond = models.ForeignKey(
Dans mon traducteur (deepl) il me met :
- personne qui répond = person who responds
- réponse de la personne = person response

Du coup puisque c'est la personne l'objet et non la réponse ça me paraît plus pertinent de mettre le verbe non ?

2021-09-30 14:12 UTC, jillro commented on agir/events/tasks.py
> +        return
Pourquoi créer les invitations en asynchrone et pas seulement les activités ?

2021-09-30 14:34 UTC, giuseppedeponte requested changes

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/activity/components/common/activity.config.js
> +              `confirmer-groupe-coorganisateur/?group=${supportGroup.id}`,
Pas possible de construire l'url côté backend et de l'envoyer dans les données de l'activité ? Ce serait beaucoup plus propre

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/components/EventSettings/EventOrganization.js
> +const [MENU_ORGANIZER, MENU_GROUP] = ["menu-organizer", "menu-group"];
```suggestion
const MENU_ORGANIZER = "menu-group";
const MENU_GROUP = "menu-organizer";
```

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/components/common/api.js
> +  inviteGroupOrganizer: "/api/evenements/:eventPk/group-organisateurs/",
```suggestion
  inviteGroupOrganizer: "/api/evenements/:eventPk/groupes-organisateurs/",
```

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/models.py
> +    )
Pas besoin d'`INVITATION` vu que ça donnera déjà `Invitation.STATUS_PENDING` et j'ai l'impression que c'est un peu une habitude dans le projet de nommer les constante NOM-DE-LA-PROP_VALUE (ex. Membership.TYPE_MEMBER)
```suggestion
    STATUS_PENDING = "pending"
    STATUS_ACCEPTED = "accepted"
    STATUS_REFUSED = "refused"

    STATUSES = (
        (STATUS_PENDING, "En attente"),
        (STATUS_ACCEPTED, "Acceptée"),
        (STATUS_REFUSED, "Refusée"),
    )
```

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/models.py
> +    )
C'est peut-être plus clair `sender` et `recipient` ?
```suggestion
    sender = models.ForeignKey(
        "people.Person",
        on_delete=models.CASCADE,
        verbose_name="Personne qui émet l'invitation",
    )
    recipient = models.ForeignKey(
        "people.Person",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="invitation_response",
        verbose_name="Personne qui répond à l'invitation",
    )
```

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/models.py
> +    )
Ça fait peut-être doublon, vu que dans la classe TimestampedModel tu as déjà la date de création et de mise à jour

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/models.py
> +                fields=["person_request", "event", "group"], name="unique",
Pourquoi cette contrainte ? 
Il faudrait pas juste avoir une seule invitation par événement et par groupe ?

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/tasks.py
> +def send_group_coorganization_invitation_notification(event_pk, group_id, member_id):
À mon avis, il faudrait plutôt créer l'invitation avant (dans la vue) et, une fois qu'elle bien créée, créer la tâche celery avec juste l'id de la nouvelle invitation en paramètre.

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/tasks.py
> +        return
Pourquoi mettre à jour l'invitation si elle existe déjà ?

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/tasks.py
> +        return
C'est voulu qu'on puisse renvoyer une invitation qui a déjà été refusée une fois ?

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/tasks.py
> +):
Tu peux utiliser l'id de l'invitation ici aussi je crois

2021-09-30 14:34 UTC, giuseppedeponte commented on agir/events/urls.py
> +        "api/evenements/<uuid:pk>/group-organisateurs/",
```suggestion
        "api/evenements/<uuid:pk>/groupes-organisateurs/",
```

2021-09-30 14:46 UTC, maxGoaz commented on agir/events/tasks.py
> +        return
Pour mettre à jour la dernière personne qui a envoyé l'invitation, si plusieurs personne essaie d'inviter un même groupe

2021-09-30 14:47 UTC, maxGoaz commented on agir/events/tasks.py
> +        return
Pour moi c'est un comportement normal, s'il y a missclick ou autre on veut pouvoir quand même accepter. Sinon ce serait comme _bloquer_ cette possibilité pour moi

2021-09-30 16:21 UTC, maxGoaz commented on agir/events/models.py
> +                fields=["person_request", "event", "group"], name="unique",
C'est vrai j'ai modifié, dans ma tête on pouvait/voulait enregistrer des invitations provenant de plusieurs personnes

2021-10-01 08:30 UTC, giuseppedeponte requested changes

2021-10-01 08:30 UTC, giuseppedeponte commented on agir/events/tasks.py
> +    except Invitation.DoesNotExist:
Le décorateur `@post_save_task` sert pour les tâches celery qui dépendent de la création d'une instance d'un modèle (comme ici, après la création d'une nouvelle invitation) - vu qu'il est possible que l'enregistrement en base de données ne soit pas encore fait au moment de l’exécution de la tâche, le décorateur traite les exceptions `DoesNotExist` et relance la tâche plusieurs fois. 
Donc pas besoin de traiter ces exceptions dans la tâche elle-même.

2021-10-01 08:30 UTC, giuseppedeponte commented on agir/events/tasks.py
> +    except Invitation.DoesNotExist:
Pareil ici, pas besoin de faire un `try..except`

2021-10-01 08:30 UTC, giuseppedeponte commented on agir/events/views/api_views.py
> +                invitation.status = Invitation.STATUS_PENDING
On peut en discuter tous ensemble, mais à mon avis si l'invitation existe déjà il faut juste renvoyer une erreur.

2021-10-01 08:42 UTC, maxGoaz commented on agir/events/tasks.py
> +    except Invitation.DoesNotExist:
:+1:

2021-10-01 10:43 UTC, giuseppedeponte requested changes
Un dernier changement, sinon ce sera ok pour moi.

2021-10-01 10:43 UTC, giuseppedeponte commented on agir/activity/components/common/activity.config.js
> +              event.routes?.inviteGroupCoorganize + `?group=${supportGroup.id}`,
`undefined + "quelque chose" = "undefinedquelque chose`
Si c'est possible que la route ne soit pas là il faudrait plutôt rajouter le contrôle sur la condition trois lignes plus haut.
D'ailleurs si tu veux on a une fonction pour ajouter des paramètres à une URL : `agir/lib/components/utils/url.js:addQueryStringParams`

2021-10-01 13:52 UTC, maxGoaz commented on agir/activity/components/common/activity.config.js
> +              event.routes?.inviteGroupCoorganize + `?group=${supportGroup.id}`,
:+1:

2021-10-01 13:56 UTC, giuseppedeponte approved these changes

2021-10-01 14:10 UTC, jillro approved these changes

2021-10-01 14:10 UTC, merged