Create contact page
lafranceinsoumise/actionpopulaire.fr pull request #1103
Opened 2021-09-28 10:42 UTC by giuseppedeponte

2021-09-28 13:21 UTC, jillro commented on agir/people/rules.py
> +@rules.predicate
doublon avec le prédicat juste au dessus non ?

2021-09-28 13:21 UTC, jillro commented on agir/people/serializers.py
> +                validated_data["meta"] = {
Y a pas moyen d'utiliser les méthodes déjà existantes ?

Par ailleurs on a pas tranché : jusqu'à présent toutes les personnes is_2022=True ont un subscriptions__NSP. L'idée de la clé NSP n'était pas d'indiquer la source de la souscription, simplement n'importe quelle information se rapportant à is_2022. L'idée de faire une clé différente n'est pas idiote, mais alors il faudra revoir certains outils de stats et vérifier que la clé NSP n'est pas utilisée ailleurs dans le code comme équivalent de "signataire pour 2022".

2021-09-28 13:27 UTC, giuseppedeponte commented on agir/people/serializers.py
> +                validated_data["meta"] = {
Normalement il peut y avoir des personnes inscrites via Action Populaire (ou même LFI) avec is_2022 = true. Pour moi le type était juste utilisé pour envoyer des emails différents. En vrai si on a besoin d'un autre format pour les statistiques on peut changer ici sans problème. J'ai regardé si on pouvait utiliser l'action `save_subscription_information` comme pour l'inscription, mais ce n'est pas tout à fait exactement le même traitement  des informations et je me suis dit que c'était plus sûr/facile de faire du code dédié pour la création de contact.

2021-09-28 13:37 UTC, giuseppedeponte commented on agir/people/rules.py
> +@rules.predicate
Presque, `is_person` vérifie que la personne connectée est la même qu'on veut modifier.
`is_a_person` vérifie juste que la personne connectée est une personne (n'importe laquelle).
Je peux changer les noms si ce n'est pas très clair et vous avez des idées

2021-09-28 14:10 UTC, jillro commented on agir/people/rules.py
> +@rules.predicate
Ou alors simplement un commentaire :) ?

2021-09-28 14:11 UTC, jillro commented on agir/people/serializers.py
> +                validated_data["meta"] = {
Ok, on reverra les outils après en fonction.

2021-09-28 14:39 UTC, giuseppedeponte commented on agir/people/rules.py
> +@rules.predicate
:+1:

2021-09-29 13:44 UTC, maxGoaz requested changes

2021-09-29 14:49 UTC, merged