Replace soft login warning toast message with modal
lafranceinsoumise/actionpopulaire.fr pull request #1117
Opened 2021-09-30 10:23 UTC by giuseppedeponte

- Add extra tags to soft login flash messages
- Display a modal instead of a toast for the ANONYMOUS_TO_SOFT_LOGIN_CONNECTION flash message

2021-09-30 14:27 UTC, maxGoaz requested changes

2021-09-30 14:27 UTC, maxGoaz commented on agir/front/components/globalContext/Toast.js
> +      />
Cela éviterait de charger ce composant sur tous les appels ?
```suggestion
      {!!softLoginToastId && <SoftLoginModal
        user={user}
        shouldShow={!!softLoginToastId}
        onClose={() => handleClear(softLoginToastId)}
      />}
```

2021-10-01 10:45 UTC, giuseppedeponte commented on agir/front/components/globalContext/Toast.js
> +      />
Vu que c'est une modale, on ne peut pas l'ajouter uniquement quand elle est visible, sinon on perd l'animation d'entrée/sortie. Et c'est un tout petit composant en réalité.

2021-10-01 10:53 UTC, maxGoaz approved these changes

2021-10-01 10:53 UTC, merged