Messages : conversations between user and group referents
lafranceinsoumise/actionpopulaire.fr pull request #1314
Opened 2021-11-09 17:23 UTC by maxGoaz

2021-12-01 16:04 UTC, giuseppedeponte requested changes

2021-12-02 14:09 UTC, giuseppedeponte submitted a review, later dismissed

2021-12-02 14:09 UTC, giuseppedeponte commented on agir/groups/actions/notifications.py
> +        recipients = Person.objects.filter(memberships__in=memberships)
Ça devrait être peut-être un peu plus rapide de chercher directement par id :
```suggestion
        recipients = Person.objects.filter(id__in=memberships.values_list("person_id", flat=True))
```

2021-12-02 15:14 UTC, jillro reviewed
Je trouve que ce is_own_organization apporte beaucoup de complexité puisque de toute façon par défaut, il fallait déjà être membre, et qu'on ajoute donc que des required_membership_type.

2021-12-02 15:14 UTC, jillro commented on agir/msgs/models.py
> +    MESSAGE_TYPE_ORGANIZATION = "Private"
Pourquoi il faut d'un côté des MESSAGE_TYPE et de l'autre des REQUIRED_MEMBERSHIP, pourquoi c'est pas une seule et même variable ?

2021-12-02 15:39 UTC, maxGoaz commented on agir/msgs/models.py
> +    MESSAGE_TYPE_ORGANIZATION = "Private"
On a reparlé de la feature et on est apparemment d'accord sur pouvoir contacter les animateurs sans pour autant être membre du groupe.

Cependant il peut en effet suffire de supprimer `message_type` du modèle tout en changeant les règles pour que cela fonctionne. Comme remplacer `is_group_member` par `is_allowed_role` par exemple.

2021-12-03 16:22 UTC, giuseppedeponte commented on agir/groups/tasks.py
> +    recipients_id = ([recipient.id] for recipient in recipients)
```suggestion
    recipients_id = [recipient.id for recipient in recipients]
```

2021-12-03 16:24 UTC, giuseppedeponte commented on agir/groups/tasks.py
> +    if message_initial.required_membership_type > Membership.MEMBERSHIP_TYPE_FOLLOWER:
Y a-t-il besoin de cette condition, vu qu'on filtre aussi sur la ligne d'après ?

2021-12-03 16:25 UTC, giuseppedeponte commented on agir/groups/tasks.py
> +        persons_allowed_id = ([person.id] for person in persons_allowed)
```suggestion
        persons_allowed_id = [person.id for person in persons_allowed]
```

2021-12-03 16:29 UTC, giuseppedeponte commented on agir/groups/views/api_views.py
> +            raise exceptions.AuthenticationFailed("Not connected")
`get_queryset` devrait juste récupérer le queryset des données à serialiser, les permission devraient être vérifier dans une autre methode ou alors avec `permission_classes`

2021-12-03 16:37 UTC, maxGoaz commented on agir/groups/tasks.py
> +    if message_initial.required_membership_type > Membership.MEMBERSHIP_TYPE_FOLLOWER:
Pour moi oui car c'est la condition qui différencie les messages privés et publiques

2021-12-03 16:41 UTC, giuseppedeponte commented on agir/msgs/migrations/0005_auto_20211203_1015.py
> +# Generated by Django 3.1.13 on 2021-12-03 09:15
C'est bizarre cette modification de migration, non ?

2021-12-03 16:41 UTC, giuseppedeponte commented on agir/msgs/views.py
> +                list_group_messages.remove(msg)
Peut-être juste faire une `rule` `view_message` et appeler ici `person.role.has_perm("msgs.view_message", msg)`.
```py
rules.add_perm(
    "msgs.view_message",
    is_authenticated_person & (is_own_message | (is_own_group_message & is_group_message_recipient)),
)
# is_authenticated_person - Est connectée
# is_own_message - Est l'auteur du message
# is_own_group_message - Est membre du groupe du message
# is_group_message_recipient - Est destinataire du message du groupe (membershipType >= msgs.membershipType)
```

2021-12-03 16:43 UTC, maxGoaz commented on agir/groups/views/api_views.py
> +            raise exceptions.AuthenticationFailed("Not connected")
Oui je n'ai justement pas compris pourquoi les `permission_classes`, qui devraient suffire, ne sont pas appelées avant le `get_queryset`

2021-12-03 16:43 UTC, giuseppedeponte commented on agir/groups/tasks.py
> +    if message_initial.required_membership_type > Membership.MEMBERSHIP_TYPE_FOLLOWER:
Mais ici on a besoin de différencier ? On veut juste savoir à qui envoyer la notification, et c'est toujours :
- l'auteur du message initial
- les membres du groupes avec membershipType > msg.membershipType
(il faudra juste supprimer l'auteur du commentaire)

2021-12-03 16:44 UTC, giuseppedeponte commented on agir/groups/tasks.py
> +    if message_initial.required_membership_type > Membership.MEMBERSHIP_TYPE_FOLLOWER:
C'est pareil pour les messages publiques et privés, non ?

2021-12-03 16:47 UTC, maxGoaz commented on agir/msgs/views.py
> +                list_group_messages.remove(msg)
Ce code est pour récupérer uniquement les messages privés, dont on a les droits de groupe, depuis la requête précédente. Je ne vois pas pourquoi d'autres règles modifieraient le retour de la requête ?

2021-12-03 16:52 UTC, giuseppedeponte commented on agir/msgs/views.py
> +        return list_group_messages
Pardon, ce n'était pas très clair. 
Ici tu pourrais faire : 
```suggestion
        return [ msg for msg in group_messages if person.role.has_perm("msgs.view_message", msg)
```
qui a l'avantage de centraliser toute la logique de qui a le droit de voir un message au même endroit, dans le fichier `rules`

2021-12-03 16:54 UTC, maxGoaz commented on agir/msgs/views.py
> +        return list_group_messages
Ah oui en effet c'est plus centralisé ! C'est plus clair :)

2021-12-03 16:57 UTC, giuseppedeponte commented on agir/groups/views/api_views.py
> +            raise exceptions.AuthenticationFailed("Not connected")
Les `object_perms_map` fonctionnent uniquement sur les endpoints avec un objet (Retrieve / Update / Delete, pas avec List ou Update) ou alors si on appelle `self.get_object` explicitiement.
Tu peux aussi ajouter des règles dans `perms_map` qui ne sont pas liées à un objet, mais juste à la requête.
Ou sinon tu peux utiliser plusieurs `permission_classes`, par ex `permission_classes=(IsAuthenticated, GroupMessagesPermissions) ` (à vérifier si ça fonctionne tel quel, je ne suis pas sûr à 100%)

2021-12-03 17:40 UTC, maxGoaz commented on agir/groups/tasks.py
> +    if message_initial.required_membership_type > Membership.MEMBERSHIP_TYPE_FOLLOWER:
Non à priori on avait choisi de ne notifier que les personnes qui membres qui ont déjà participé à la discussion pour les messages publics

2021-12-03 17:42 UTC, maxGoaz commented on agir/groups/tasks.py
> +    if message_initial.required_membership_type > Membership.MEMBERSHIP_TYPE_FOLLOWER:
(C'est la requête du else en dessous)

2021-12-03 17:44 UTC, maxGoaz commented on agir/groups/views/api_views.py
> +            raise exceptions.AuthenticationFailed("Not connected")
Hmm j'avais déjà essayé d'ajouter le IsAuthenticated mais cela ne change rien, sachant qu'il faut déjà être authentifié dans la permission `GroupMessagesPermissions`
Le `self.get_object` déclenche une récursion infinie à cet endroit, je cherche autre chose !

2021-12-07 16:18 UTC, jillro requested changes

2021-12-07 16:18 UTC, jillro commented on agir/groups/views/api_views.py
> +class GroupMessagesPrivateAPIView(GroupMessagesAPIView):
Je pense que ça devrait être le même enpoint d'API avec des valeurs différentes dans le body.

2021-12-07 16:18 UTC, jillro commented on agir/groups/views/api_views.py
> +                new_comment_notifications(comment)
Est-ce qu'on pouvait pas garder une seule method et affiner son contenu en fonction du cas ?

2021-12-07 16:18 UTC, jillro commented on agir/msgs/components/MessagePage/MessagePage.js
> +const MessagePage = ({ messagePk, groupPk }) => {
tout ce groupPk peut sauter maintenant, ça reste juste de la première version du design non ?

2021-12-07 16:44 UTC, maxGoaz commented on agir/front/components/formComponents/MessageModal/MessageStep.js
> +    privateGroupId,
C'était pour utiliser une seule variable pour connaître à la fois si le message est privé et si le groupe est dans ceux de l'utilisateur. L'id du groupe est utile pour afficher un message contextuel. Un autre nom serait meilleur ?

2021-12-07 16:46 UTC, maxGoaz commented on agir/front/components/formComponents/MessageModal/Modal.js
> +    }
`maySend` bloque ou non les fonctionnalités pour publier un message (bouton désactiver etc).
Or pour un message privé on ne veut pas avoir ces bloquages et l'envoyer directement

2021-12-07 16:52 UTC, maxGoaz commented on agir/front/components/genericComponents/MessageCard.js
> +    message.requiredMembershipType > MEMBERSHIP_TYPES.MEMBER;
Personnellement je trouve ça moins long et plus explicite de stocker dans une même variable booléenne nommée pour l'utiliser dans les conditions qui suivent. Peut-être est-elle mal nommée ? `isPrivateMessage` ?

2021-12-07 16:53 UTC, maxGoaz commented on agir/groups/views/api_views.py
> +class GroupMessagesPrivateAPIView(GroupMessagesAPIView):
J'avais justement commencé avec le même endPoint, mais pour des raisons de permissions, des discussions avec @giuseppedeponte m'ont conforté à en faire un autre.
En fait, pour poster des messages privé on veut seulement être authentifié contrairement aux autre types de messages

2021-12-07 17:01 UTC, maxGoaz commented on agir/groups/views/api_views.py
> +                new_comment_notifications(comment)
Si on peut toujours d'ailleurs :)
J'ai choisi de séparer en 2 fonctions les notifications car j'y trouvais trop de différences et que la fonction devenait vraiment très longue. 
`new_comment_notifications` fait déjà 54 lignes

2021-12-08 11:07 UTC, jillro commented on agir/front/components/genericComponents/MessageCard.js
> +    message.requiredMembershipType > MEMBERSHIP_TYPES.MEMBER;
C'est plus explicite que si le nom de ta variable est plus explicite que ta condition, et ça ne me semble ni être le cas de `isOrganizationMessage` (on a l'impression qu'on parle d'une organisation, laquelle ?) ni de `isPrivateMessage` (puisque y a pas de message public/privé). `isOrganizerMessage` peut-être ?

2021-12-08 11:08 UTC, jillro commented on agir/groups/views/api_views.py
> +class GroupMessagesPrivateAPIView(GroupMessagesAPIView):
J'avoue que je n'ai pas testé, mais ça me semblerait tellement plus clair que ce soit géré dans les rules ?

2021-12-08 11:11 UTC, jillro commented on agir/groups/views/api_views.py
> +                new_comment_notifications(comment)
À la limite tu crées une fonction que tu appelles depuis new_comment_notifications si tu veux pas que celle-ci devienne trop longue, mais là en l'occurence tu as deux fonctions avec la même signature et même paramètres, que tu appelles alternativement en fonction d'une condition sur un des paramètres de ces fonctions, c'est clairement que la condition devrait être dans la fonction.

2021-12-08 14:32 UTC, maxGoaz commented on agir/groups/views/api_views.py
> +class GroupMessagesPrivateAPIView(GroupMessagesAPIView):
Si c'est le même endPoint pour `POST` un nouveau message, je ne vois pas comment différencier dans les `rules` s'il est privé ou non. Sinon il faudrait redéfinir la méthode post dans `GroupMessageAPIView` et gérer les permissions à l'intérieur, ce que j'avais fait au départ mais cela ajoutait beaucoup de code sans être plus clair

2021-12-09 11:14 UTC, jillro commented on agir/front/components/formComponents/MessageModal/Modal.js
> +    }
Pour un message privé on s'en fout que isLoading soit vrai ?

2021-12-09 11:14 UTC, jillro commented on agir/front/components/formComponents/MessageModal/Modal.js
> +    }
J'ai l'impression qu'on a juste pas besoin d'un selectedEvent mais que du coup la condition doit être réécrite.

2021-12-09 11:14 UTC, jillro commented on agir/front/components/formComponents/MessageModal/Modal.js
> +          ) : !selectedEvent && !privateGroupId ? (
La valeur n'est utilisée que comme boléenne dans le composant, la variable devrait s'appeler autrement.

2021-12-09 11:14 UTC, jillro commented on agir/msgs/components/MessagePage/MessagePage.js
> +  const { data: group } = useSWR(getGroupEndpoint("getGroup", { groupPk }));
Faut le supprimer non ?

2021-12-09 13:21 UTC, maxGoaz commented on agir/front/components/formComponents/MessageModal/Modal.js
> +          ) : !selectedEvent && !privateGroupId ? (
Non on l'utilise en la passant au composant MessageStep :-/

2021-12-16 11:33 UTC, jillro approved these changes

2021-12-16 11:33 UTC, merged