Donations : refactor and feedbacks
lafranceinsoumise/actionpopulaire.fr pull request #1326
Opened 2021-11-15 17:23 UTC by maxGoaz

2021-11-15 17:44 UTC, jillro requested changes

2021-11-15 17:44 UTC, jillro commented on agir/donations/serializers.py
> +class CreateSessionDonationSerializer(serializers.Serializer):
DonationSession parce que c'est de l'anglais :)

2021-11-15 17:44 UTC, jillro commented on agir/donations/serializers.py
> +    paymentTimes = serializers.ChoiceField(
Je ne comprends pas pourquoi c'est pas `monthly` et un boolean ?

2021-11-15 17:44 UTC, jillro commented on agir/donations/components/donationPage/InformationsStep.js
```suggestion
```

2021-11-15 17:44 UTC, jillro commented on agir/donations/components/donationPage/InformationsStep.js
> +      ) {
```suggestion
  if (profile?.newsletters && Array.isArray(profile.newsletters)) {
    if (
      profile.newsletters.includes("2022") &&
      profile.newsletters.includes("2022_exceptionnel")
    ) {
      hasNewsletter = true
    }
  }
```

2021-11-15 17:44 UTC, jillro commented on agir/donations/components/donationPage/InformationsStep.js
> +      ) {
Je ne crois pas qu'il y ait besoin d'utiliser un useEffect et un état ici, puisque hasNewsletter dépend uniquement de profile.

2021-11-15 17:49 UTC, maxGoaz commented on agir/donations/serializers.py
> +    paymentTimes = serializers.ChoiceField(
Si demain on veut faire un paiement annuel par exemple ?

2021-11-15 17:50 UTC, maxGoaz commented on agir/donations/components/donationPage/InformationsStep.js
Pourquoi faut-il supprimer ce state ?

2021-11-15 17:51 UTC, maxGoaz commented on agir/donations/components/donationPage/InformationsStep.js
> +      ) {
Ok je comprends mieux pourquoi supprimer l'état alors :)

2021-11-15 18:20 UTC, jillro requested changes

2021-11-15 18:20 UTC, jillro commented on agir/donations/views/api_views.py
> +            ):
Du coup ça faudrait le supprimer non ?

2021-11-16 10:47 UTC, jillro submitted a review, later dismissed

2021-11-16 10:47 UTC, jillro commented
@giuseppedeponte tu peux faire un double-check ?

2021-11-16 11:35 UTC, giuseppedeponte approved these changes

2021-11-16 11:39 UTC, merged