Message : panel participants
lafranceinsoumise/actionpopulaire.fr pull request #1526
Opened 2022-01-06 14:54 UTC by maxGoaz

2022-01-06 15:07 UTC, giuseppedeponte commented on agir/msgs/serializers.py
> +    def get_participants(self, obj):
Vu qu'on affiche les participants dans un panneau, ce ne serait pas plus optimisé de faire un endpoint dédié pour récupérer ces informations uniquement lorsqu'on en a besoin ?

2022-01-07 10:31 UTC, giuseppedeponte requested changes

2022-01-07 10:31 UTC, giuseppedeponte commented on agir/groups/views/api_views.py
> +
Je crois qu'on peut utiliser plus le comportement par défaut de `Rest Framework` ici, en faisant une chose comme ça : 
```py

class SupportGroupMessageParticipantSerializer(serializers.ModelSerializer):
    active = serializers.SerializerMethodField(read_only=True)
    commentAuthors = serializers.SerializerMethodField(
        read_only=True, method_name="get_comment_authors"
    )
    total = serializers.SerializerMethodField(read_only=True)

    def get_comment_authors(self, message):
        comment_authors = list(message.comments.values_list("author_id", flat=True))
        comment_authors = set([message.author.id] + comment_authors)

        return list(comment_authors)

    def get_total(self, message):
        return (
            message.supportgroup.memberships.filter(
                Q(membership_type__gte=message.required_membership_type)
                | Q(person_id=message.author_id)
            )
            .distinct()
            .count()
        )

    def get_active(self, message):
        active_memberships = (
            message.supportgroup.memberships.filter(
                Q(membership_type__gte=message.required_membership_type)
            )
            .filter(
                Q(membership_type=Membership.MEMBERSHIP_TYPE_REFERENT)
                | Q(person_id__in=message.comments.values_list("author_id", flat=True))
                | Q(person_id=message.author_id)
            )
            .annotate(
                has_commented=Exists(
                    message.comments.filter(author_id=OuterRef("person_id"))
                )
            )
            .distinct()
        )

        return [
            {
                "id": membership.person_id,
                "displayName": membership.person.display_name,
                "membershipType": membership.membership_type,
                "isAuthor": message.author_id == membership.person_id,
                "isInComments": membership.has_commented,
                "image": membership.person.image.thumbnail.url
                if (membership.person.image and membership.person.image.thumbnail)
                else None,
                "gender": membership.person.gender,
            }
            for membership in active_memberships
        ]

    class Meta:
        model = SupportGroupMessage
        fields = ("active", "commentAuthors", "total")


class GroupMessageParticipantsAPIView(RetrieveAPIView):
    serializer_class = SupportGroupMessageParticipantSerializer
    permission_classes = (IsAuthenticated,)
    queryset = SupportGroupMessage.objects.all()
```
plutôt avec un Serializer qui s'occupe de formatter les données et une view qui ne fait que retrouver le message et passer les données au serializer. 

En règle générale, je crois qu'il vaut mieux éviter d'écraser toute la méthode `get` (ou `post`, `patch`, ...) d'une view, car on risque de perdre certaines fonctionnalités sans s'en rendre compte. Dans la view qu tu avais fait, par exemple, vu qu'on n'appelait plus du tout la méthode `get_object`, les permissions de la personne pour le message n'étaient jamais vérifiées.

2022-01-07 11:35 UTC, maxGoaz commented on agir/groups/views/api_views.py
> +
C'est en effet plus propre de cette manière. Seulement cela fait un peu plus de requêtes non ?
Par exemple le `total` était retourné avec len(persons) dans ma view ?

Aussi pour les permissions il me semblaient qu'elles étaient bien valides avec `GroupMessagesPermissions` ?

2022-01-07 11:54 UTC, giuseppedeponte commented on agir/groups/views/api_views.py
> +
Normalement c'est à l'intérieur de `get_object` qu'on appelle la methode `check_object_permissions` qui utilise la valeur de `permissions_classes` pour vérifier les permissions sur un objet (ici le message).
 
 Pour le nombre / la performance des requêtes, tu peux faire des essais pour voir s'il y a une meilleure manière de faire, mais normalement une requête `count` en plus ça ne devrait pas changer enormement.
 
Avec quelques requêtes en moins ça pourrait être comme ça : 
```py

class SupportGroupMessageParticipantSerializer(serializers.ModelSerializer):
    active = serializers.SerializerMethodField(read_only=True)
    commentAuthors = serializers.SerializerMethodField(
        read_only=True, method_name="get_comment_authors"
    )
    total = serializers.SerializerMethodField(read_only=True)

    def get_comment_authors(self, message):
        comment_authors = list(message.comments.values_list("author_id", flat=True))
        comment_authors = set([message.author_id] + comment_authors)

        return list(comment_authors)

    def get_total(self, message):
        return (
            message.supportgroup.memberships.filter(
                Q(membership_type__gte=message.required_membership_type)
                | Q(person_id=message.author_id)
            )
            .distinct()
            .count()
        )

    def get_active(self, message):
        active_memberships = (
            message.supportgroup.memberships.filter(
                Q(membership_type__gte=message.required_membership_type)
            )
            .filter(
                Q(membership_type=Membership.MEMBERSHIP_TYPE_REFERENT)
                | Q(person_id__in=message.comments.values_list("author_id", flat=True))
                | Q(person_id=message.author_id)
            )
            .annotate(
                has_commented=Exists(
                    message.comments.filter(author_id=OuterRef("person_id"))
                )
            )
            .distinct()
        )

        return [
            {
                "id": membership.person_id,
                "displayName": membership.person.display_name,
                "membershipType": membership.membership_type,
                "isAuthor": message.author_id == membership.person_id,
                "isInComments": membership.has_commented,
                "image": membership.person.image.thumbnail.url
                if (membership.person.image and membership.person.image.thumbnail)
                else None,
                "gender": membership.person.gender,
            }
            for membership in active_memberships.select_related("person")
        ]

    class Meta:
        model = SupportGroupMessage
        fields = ("active", "commentAuthors", "total")


class GroupMessageParticipantsAPIView(RetrieveAPIView):
    serializer_class = SupportGroupMessageParticipantSerializer
    permission_classes = (IsAuthenticated,)
    queryset = SupportGroupMessage.objects.all().select_related("supportgroup")
```
Si tu regardes dans Silk, (en ajoutant le paramètre `silk=1` à l'URL et en allant ensuite sur la page `/silk/requests/`), la première version fait 8 requêtes (sans jointures) et la deuxième 4 (deux avec une jointure).

2022-01-07 14:20 UTC, giuseppedeponte approved these changes

2022-01-07 15:11 UTC, merged