Mark all messages as read in only two db queries (instead of two for each message)
lafranceinsoumise/actionpopulaire.fr pull request #1718
Opened 2022-02-09 15:18 UTC by giuseppedeponte

2022-02-09 15:48 UTC, maxGoaz requested changes

2022-02-09 15:48 UTC, maxGoaz commented on agir/msgs/views.py
> +            ).update(modified=timezone.now())
Le ignore_conflicts permet de conserver l'unicité des `recipient` + `message` c'est ça ? :)
On peut encore gagner un peu de temps en inversant l'ordre des deux opérations en base je pense, puisque le update n'a pas besoin de s'appliquer sur les nouveaux `SupportGroupMessageRecipient` ?


```
SupportGroupMessageRecipient.objects.filter(
                message__in=messages, recipient=person
            ).update(modified=timezone.now())

SupportGroupMessageRecipient.objects.bulk_create(
            SupportGroupMessageRecipient.objects.update_or_create(
                (
                message=message,
                    SupportGroupMessageRecipient(message=message, recipient=person)
                recipient=person,
                    for message in messages
                ),
                ignore_conflicts=True,
            )
)
```

2022-02-09 15:53 UTC, giuseppedeponte commented on agir/msgs/views.py
> +            ).update(modified=timezone.now())
> Le ignore_conflicts permet de conserver l'unicité des recipient + message c'est ça ? :)
Oui, la méthode `create` échoue dès qu'il y a une erreur, par exemple s'il y a un conflit sur une contrainte de la table en bdd. Avec `ignore_conflicts=True`, ces erreurs ne bloquent pas la création des autres lignes.

2022-02-09 15:54 UTC, giuseppedeponte commented on agir/msgs/views.py
> +            ).update(modified=timezone.now())
`update_or_create` fonctionne uniquement avec un seul objet normalement. Mais effectivement je peux voir si le update renvoie les objets mis à jour pour réduire les requêtes

2022-02-10 10:52 UTC, maxGoaz approved these changes

2022-02-10 10:52 UTC, merged