Events : allow joining as a group
lafranceinsoumise/actionpopulaire.fr pull request #1794
Opened 2022-02-23 14:40 UTC by maxGoaz

2022-03-04 16:18 UTC, giuseppedeponte requested changes

2022-03-04 16:18 UTC, giuseppedeponte commented on agir/events/serializers.py
> +        return groups
```suggestion
        if user.is_anonymous or user.person is None:
            return obj.group_attendees.all().annotate(isManager=Value(False)).values("id", "name", "isManager")
        return obj.group_attendees.all().annotate(isManager=Exists(
            person.memberships.filter(supportgroup_id=OuterRef("id"),
                                      membership_type__gte=Membership.MEMBERSHIP_TYPE_MANAGER)
        )).values("id", "name", "isManager")
```

2022-03-04 16:18 UTC, giuseppedeponte commented on agir/front/components/genericComponents/EventCard.js
> +    return <></>;
```suggestion
    return null;
```

2022-03-04 16:18 UTC, giuseppedeponte commented on agir/front/components/genericComponents/EventCard.js
> +          Le groupe&nbsp;<b>{groupsAttendees[0].name}</b>
```suggestion
          Votre groupe&nbsp;<strong>{fromUserGroups[0].name}</strong>
        </>
      ) : (
        <>
          Le groupe&nbsp;<strong>{groupsAttendees[0].name}</strong>
```

2022-03-04 16:18 UTC, giuseppedeponte commented on agir/front/components/genericComponents/EventCard.js
> +};
On peut mettre ce composant dans son propre fichier ?

2022-03-04 16:18 UTC, giuseppedeponte commented on agir/events/models.py
> +        "groups.SupportGroup", related_name="event_groups", through="GroupAttendee"
```suggestion
        "groups.SupportGroup", related_name="attended_event", through="GroupAttendee"
```

2022-03-04 16:18 UTC, giuseppedeponte commented on agir/groups/utils.py
> +    return events
```suggestion
def get_events_with_group(queryset, supportgroup):
    return queryset.filter(
        Q(organizers_groups__in=[supportgroup])
        | Q(groups_attendees__in=[supportgroup])
    )
```

2022-03-04 17:29 UTC, maxGoaz commented on agir/activity/components/ActivityPage/ActivityCard/GenericCard.js
> +      );
Entre lesquelles deux, les nouvelles ?
Il y a `new-group-attendee` quand un groupe rejoint un événement que j'organise :
`{SupportGroup} s'est inscrit à votre événement {Event}`
Et celle là, `group-join-event` quand un des groupes dont je suis membre (< referents) rejoint un événement

2022-03-04 17:31 UTC, maxGoaz commented on agir/events/components/eventPage/AddGroupAttendee.js
> +  const redList = eventGroupsId.concat(eventGroupsAttendeesId);
Qu'est-ce que tu as contre les rouquins ? 😮

2022-03-07 09:06 UTC, giuseppedeponte commented on agir/events/components/eventPage/AddGroupAttendee.js
> +  const redList = eventGroupsId.concat(eventGroupsAttendeesId);
Rien ! Au temps pour moi : il paraît qu'en français on peut dire aussi une "liste rouge" dans ce sens-là : https://fr.wikipedia.org/wiki/Liste_rouge

2022-03-07 09:11 UTC, giuseppedeponte commented on agir/activity/components/ActivityPage/ActivityCard/GenericCard.js
> +      );
Ok, j'ai compris. Je trouve que `new-group-attendee` c'est assez compréhensible (ça ressemble à `new-attendee`).
`group-join-event` c'est moins clair, mais je n'ai pas trop d'autres idées. Peut-être `new-event-participation-my-groups` (un peu comme `new-event-my-groups`) ?

2022-03-14 11:07 UTC, giuseppedeponte approved these changes

2022-03-14 11:29 UTC, giuseppedeponte approved these changes

2022-03-14 13:28 UTC, merged