Fix sentry 2937
lafranceinsoumise/actionpopulaire.fr pull request #2020
Opened 2022-04-01 15:54 UTC by maxGoaz

2022-04-01 16:00 UTC, giuseppedeponte requested changes

2022-04-01 16:10 UTC, maxGoaz commented on agir/groups/views/api_views.py
> +        membershipType = int(request.data.get("membershipType", 0))
Mais membershipType ne peut valoir `None` ici ?
Il vaut 0 si non défini avec `request.data.get("membershipType", 0)`

2022-04-01 16:12 UTC, giuseppedeponte commented on agir/groups/views/api_views.py
> +        membershipType = int(request.data.get("membershipType", 0))
![image](https://user-images.githubusercontent.com/29723122/161301765-e422ac56-6662-4025-90a2-b719beef372b.png)
Et pourtant c'est ça l'erreur : on ne peut pas comparer `None` avec un entier

2022-04-04 08:49 UTC, giuseppedeponte approved these changes

2022-04-04 09:59 UTC, merged