MaximeG/connexion
lafranceinsoumise/actionpopulaire.fr pull request #338
Opened 2021-03-11 10:51 UTC by maxGoaz

2021-03-11 14:14 UTC, giuseppedeponte commented on agir/front/components/app/Connexion.js
> +import bgMobile from "../genericComponents/images/login_bg_mobile.svg";
Normalement on a un composant pour afficher le logo, `agir/front/components/genericComponents/LogoAP.js`, à voir si on peut l'utiliser ici aussi

2021-03-11 14:14 UTC, giuseppedeponte commented on agir/front/components/app/Connexion.js
> +import logoMobile from "../genericComponents/logos/action-populaire_mini.svg";
```suggestion
import logoDesktop from "@agir/front/genericComponents/logos/action-populaire.svg";
import logoMobile from "@agir/front/genericComponents/logos/action-populaire_mini.svg";
```

2021-03-11 14:14 UTC, giuseppedeponte commented on agir/front/components/app/Connexion.js
> +import facebookImg from "../genericComponents/images/facebook_circle.svg";
```suggestion
import facebookImg from "@agir/front/genericComponents/images/facebook_circle.svg";
```

2021-03-11 14:14 UTC, giuseppedeponte commented on agir/front/components/app/Connexion.js
> +`;
Pas besoin de ce composant vu que tu définis des styles en ligne à chaque fois, non ?

2021-03-11 15:47 UTC, jillro commented on agir/front/components/app/Connexion.js
> +    <Button className="button-facebook">
La meilleure approche c'est de définir un autre styled component 

```js
const FacebookButton = styled(Button)``
```
puis dans ton autre composant
```js

const SuperComponent = styled.div`
  & > ${FacebookButton} {
  /* whatever style you want */
  }
`;
```

2021-03-12 13:43 UTC, jillro requested changes

2021-03-12 13:43 UTC, jillro commented on agir/front/components/app/Connexion/Connexion.js
> +// import { ResponsiveLayout } from "@agir/front/genericComponents/grid";
penses à bien nettoyer touy ton code commenté

2021-03-12 13:43 UTC, jillro commented on agir/front/components/app/Connexion/Connexion.js
> +              >
Essaie d'applatir tout ça dans une flexbox et d'en faire un styled component.

2021-03-12 13:43 UTC, jillro commented on agir/front/components/app/Connexion/Connexion.js
> +          <div style={{ width: "100%", height: "450px" }}></div>
On a un composant Spacer, par ailleurs moi j'aime vraiment pas ça sémantiquement, les paddings ça marche bien aussi :)

2021-03-12 13:43 UTC, jillro commented on agir/front/components/app/Connexion/Connexion.js
> +              className="mobile-only"
on évite vraiment les classes, et on maximise aussi la réutilisation des composants (on a déjà une appli bien lourde, il va falloir qu'on se discipline tous là dessus)

tu as plein de trucs à ta dispo dans `grid.js` notamment un composant `Hide` que tu peux utiliser

2021-03-12 13:43 UTC, jillro commented on agir/front/components/app/Connexion/Login.js
> +};
Là il faut faire un styled component.

2021-03-12 13:43 UTC, jillro commented on agir/front/components/app/Connexion/Signin.js
> +        politique de conservation des données
il faut mettre le lien https://infos.actionpopulaire.fr/mentions-legales/

2021-03-12 13:52 UTC, giuseppedeponte commented on agir/front/components/app/Connexion/Signin.js
> +          onChange={(e) => handleChange(e, "email")}
C'est mieux d'éviter de définir des fonctions dans le render, pour éviter des mise à jour inutiles. Tu peux par exemple, passer une prop `name` à TextField et récupérer la valeur dans `handleChange` (`e.target.name`)

2021-03-12 13:53 UTC, giuseppedeponte commented on agir/front/components/app/Connexion/Signin.js
> +      </ul>
On aura bientôt un composant custom pour les inputs radio (on l'a mis en prod hier, mais on n'a pas encore mis à jour cette branche)

2021-03-12 16:08 UTC, maxGoaz commented on agir/front/components/app/Connexion.js
> +import bgMobile from "../genericComponents/images/login_bg_mobile.svg";
Du coup j'ai utilisé LogoAP pour le logo desktop mais pas pour le mini sans texte qui n'existait pas (!= small).
Les lignes d'import ci-dessus sont des imports de nouveaux backgrounds je crois pour le coup (les briques diagonales jaunes rouge violette)

2021-03-12 16:10 UTC, maxGoaz commented on agir/front/components/app/Connexion.js
> +`;
Je l'ai supprimé partout où il avait des styles en plus !

2021-03-12 16:17 UTC, maxGoaz commented on agir/front/components/app/Connexion/Connexion.js
> +          <div style={{ width: "100%", height: "450px" }}></div>
J'ai mis du padding du coup j'avoue ! Je vais regarder le Spacer pour d'autres occasions

2021-03-12 16:18 UTC, maxGoaz commented on agir/front/components/app/Connexion/Connexion.js
> +              className="mobile-only"
Ca marche j'ai utilisé le Hide

2021-03-12 16:19 UTC, maxGoaz commented on agir/front/components/app/Connexion/Signin.js
> +          onChange={(e) => handleChange(e, "email")}
C'est fait ! :)

2021-03-12 16:19 UTC, maxGoaz commented on agir/front/components/app/Connexion/Signin.js
> +      </ul>
Je laisse tel quel en attendant alors, mais je pourrai le mettre à la place

2021-03-15 17:03 UTC, jillro reviewed
quelques commentaires

2021-03-15 17:03 UTC, jillro commented on agir/front/components/app/routes.config.js
> +    // Component: IntroAppPage,
commentaire

2021-03-16 09:41 UTC, giuseppedeponte approved these changes

2021-03-16 09:42 UTC, merged