Login - Check code - Logout API endpoints
lafranceinsoumise/actionpopulaire.fr pull request #339
Opened 2021-03-11 15:42 UTC by giuseppedeponte

2021-03-12 09:46 UTC, jillro requested changes
quelques bouts de code en trop mais sinon ça marche !

2021-03-12 09:46 UTC, jillro commented on agir/authentication/views/api_views.py
> +class LoginAPIView(CreateAPIView):
Pourquoi y a-t-il besoin de `CreateAPIView` ? `APIView` ne suffit pas ?

2021-03-12 09:46 UTC, jillro commented on agir/authentication/views/api_views.py
> +    def authenticate(self, email, role):
À ce moment là la personne est déjà authentifiée, mais pas encore connectée. Du coup `login` ou `do_login` si possible, pour éviter la confusion avec le authenticate importé plus haut qui check effectivement l'authentification.

2021-03-12 09:46 UTC, jillro commented on agir/authentication/views/api_views.py
> +        if role.person.primary_email.bounced:
la condition devrait être plus bas, il faut débouncer n'importe qu'elle adresse utilisée avec succès pour la connexion, qu'elle soit primary ou pas, et ensuite la passer en primary si l'adresse primary actuelle est bounced

2021-03-12 09:46 UTC, jillro commented on agir/authentication/views/api_views.py
> +    queryset = Person.objects.all()
ligne non nécessaire

2021-03-12 09:46 UTC, jillro commented on agir/authentication/views/api_views.py
> +    queryset = Person.objects.all()
ligne non nécessaire

2021-03-12 14:06 UTC, jillro approved these changes

2021-03-12 16:27 UTC, jillro approved these changes

2021-03-12 16:27 UTC, jillro commented on agir/people/urls.py
> +    path("api/profil/", api.PersonProfileAPIView.as_view(), name="api_people_profile",),
est-ce qu'on la placerait sous /api/user/profile ?

2021-03-12 16:50 UTC, giuseppedeponte commented on agir/people/urls.py
> +    path("api/profil/", api.PersonProfileAPIView.as_view(), name="api_people_profile",),
Oui, on peut, effectivement c'est l'utilisateur connecté.
Par contre on a des URLs d'API moitié en anglais et moitié en français...

2021-03-15 16:21 UTC, jillro approved these changes

2021-03-15 17:20 UTC, jillro approved these changes

2021-03-15 17:32 UTC, merged