Maxime g/event visio conf
lafranceinsoumise/actionpopulaire.fr pull request #430
Opened 2021-04-01 09:03 UTC by maxGoaz

Mise à jour du modèle Event
Composant VisioConferenceField
Génération auto du lien jisty
Affichage aux différents endroits

2021-04-01 09:57 UTC, giuseppedeponte submitted a review, later dismissed

2021-04-01 15:27 UTC, jillro requested changes
C'est du détail mais nommer le champ visio_conf_url en online_url ou autre chose de plus génrique, car il ne sera pas limité à la visio-conférence.

2021-04-01 16:55 UTC, giuseppedeponte requested changes
Pour éviter les confusions, ce serait bien de renommer le champs aussi côté front ~`visioConfUrl`~ => `onlineUrl`

2021-04-02 13:31 UTC, jillro approved these changes

2021-04-02 13:32 UTC, jillro approved these changes

2021-04-02 13:33 UTC, giuseppedeponte approved these changes

2021-04-02 13:33 UTC, merged