Maxime g/share card
lafranceinsoumise/actionpopulaire.fr pull request #431
Opened 2021-04-01 09:34 UTC by maxGoaz

2021-04-01 10:03 UTC, giuseppedeponte requested changes
Attention, je crois que tu as utilisé la même branche que pour le ticket de la visio-conférence. C'est mieux de créer une nouvelle branche pour chaque ticket.

2021-04-01 10:03 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ShareCard.js
> +            target="_blank"
```suggestion
            target="_blank"
            rel="noopener noreferrer"
```

2021-04-01 10:03 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ShareCard.js
> +            target="_blank"
```suggestion
            target="_blank"
            rel="noopener noreferrer"
```

2021-04-01 14:08 UTC, giuseppedeponte commented
Ok, pour les corrections, par contre il y a toujours un problème avec ta branche. 
Tu peux créer une nouvelle branche à partir de `origin/staging` et faire un `git cherry-pick` des deux derniers commits, ou alors faire un `git rebase -i origin/staging` et supprimer les commits en trop.

2021-04-02 13:52 UTC, maxGoaz commented
@giuseppedeponte En effet j'étais reparti de la branche "EventVisio" au lieu de staging. Maintenant qu'elle est mergée il n'y a plus que les commit de la SharedCard qui diffèrent de staging normalement !

2021-04-02 15:05 UTC, closed without merging