feat: display custom date for pending events
lafranceinsoumise/actionpopulaire.fr pull request #443
Opened 2021-04-06 08:42 UTC by maxGoaz

2021-04-06 16:02 UTC, giuseppedeponte requested changes

2021-04-06 16:02 UTC, giuseppedeponte commented on agir/front/components/genericComponents/EventCard.js
> +    : displayIntervalStart(schedule);
Pas besoin de recalculer `eventDate` à chaque render :
```suggestion
    const eventDate = React.useMemo(() => {
       const now = DateTime.local();
	    const pending = now >= schedule.start && now <= schedule.end;
	  
	    return pending
	      ? displayIntervalEnd(schedule)
	      : displayIntervalStart(schedule);
	}, [schedule])
```

2021-04-07 09:03 UTC, maxGoaz commented on agir/front/components/genericComponents/EventCard.js
> +    : displayIntervalStart(schedule);
Mais à chaque render la valeur de 'now' sera différente et donc fera différer 'pending' non ?

2021-04-07 09:10 UTC, giuseppedeponte commented on agir/front/components/genericComponents/EventCard.js
> +    : displayIntervalStart(schedule);
Oui, effectivement tu peux aussi garder la déclaration de `now` en dehors du hook pour que la date se mette à jour automatiquement à chaque render, même si ça ne sera pas forcément très compréhensible pour l'utilisateur, vu que la date changera de manière aléatoire selon si le composant se met à jour ou pas.

2021-04-07 09:12 UTC, giuseppedeponte approved these changes

2021-04-07 09:12 UTC, giuseppedeponte commented on agir/front/components/genericComponents/EventCard.js
> +    : displayIntervalStart(schedule);
Et si la valeur de `now` change à chaque render il n'y aura effectivemnt plus besoin de mettre tout ça dans un `useMemo`. Je te laisse voir, mais sinon c'est ok pour moi.

2021-04-07 09:15 UTC, merged