inactive user don't receive emails anymore
lafranceinsoumise/actionpopulaire.fr pull request #483
Opened 2021-04-15 13:13 UTC by Ben-Ji-L

I use break instruction but I don't know if it is the cleaner way to quit the function,

2021-04-15 14:30 UTC, giuseppedeponte requested changes

2021-04-15 14:30 UTC, giuseppedeponte commented on agir/lib/mailing.py
> +                    break
```suggestion
                    continue
```
`break` arrête la boucle complètement, alors que `continue` n'arrête pas la boucle mais passe directement à l’itération suivante

2021-04-15 14:39 UTC, giuseppedeponte commented on agir/lib/mailing.py
> +                recipient.ensure_role_exists()
Je ne suis pas sûr qu'il y ait besoin de faire ça. 
@jillro Qu'est-ce que tu en penses ?

2021-04-15 15:21 UTC, Ben-Ji-L commented on agir/lib/mailing.py
> +                recipient.ensure_role_exists()
Je ne sais pas quelles sont les chances que le cas se présente en prod, je l'ai mis par sécurité et parce que c'est nécessaire aux tests

2021-04-16 09:02 UTC, jillro requested changes

2021-04-19 10:38 UTC, giuseppedeponte submitted a review, later dismissed

2021-04-19 12:07 UTC, giuseppedeponte submitted a review, later dismissed

2021-04-19 12:09 UTC, Ben-Ji-L reviewed
reformat files

2021-04-19 15:23 UTC, jillro requested changes
Bravo ! La logique est ici implémentée pour les mails transactionnels :) (à un changement près, voir commentaire plus haut). Il faut ajouter la même logique dans les filtres des `Segment` qui servent à l'envoi de mail en masse, en excluant systématiquement les personnes ayant un role et  pour lequel il est inactif.

2021-04-19 15:23 UTC, jillro commented on agir/lib/mailing.py
> +                if recipient.role is None or recipient.role.is_active is False:
Changement de programme. Il peut y avoir des personnes sans role à qui on veut écrire. Les seuls personnes qu'il faut exclure sont les personnes qui ont un role et pour lequel il est inactif.

2021-04-19 15:50 UTC, Ben-Ji-L commented on agir/lib/mailing.py
> +                if recipient.role is None or recipient.role.is_active is False:
En regardant `Segment` je vois que les utilisateurs inactifs sont déjà exclus du queryset, le test : 
` test_person_with_disabled_account_not_in_segment` semble vérifier que c'est bien le cas.

2021-04-19 15:58 UTC, jillro commented on agir/lib/mailing.py
> +                if recipient.role is None or recipient.role.is_active is False:
Ok je viens de voir, déjà corrigé en décembre en effet. Il y a donc juste le changement sur send_mosaico_email à faire :)

2021-04-19 16:12 UTC, jillro requested changes

2021-04-19 16:27 UTC, jillro approved these changes

2021-04-19 16:29 UTC, jillro requested changes

2021-04-19 16:29 UTC, jillro commented on agir/people/tests/test_tasks.py
> +        self.assertEqual(len(mail.outbox), 1)
Attention, on ne termine jamais un fichier sans retour ligne à la fin de la dernière ligne.

2021-04-19 16:50 UTC, jillro approved these changes

2021-04-20 09:51 UTC, merged