on mobile create subheader with the title of the current page
lafranceinsoumise/actionpopulaire.fr pull request #529
Opened 2021-04-23 08:46 UTC by Ben-Ji-L

les éléments sont bien placés à gauche mais le logo AP devrait etre au centre

2021-04-23 10:12 UTC, giuseppedeponte commented on agir/front/components/allPages/TopBar/TopBar.js
> +  const { pathname } = useLocation();
On utilise la top bar sur toutes les pages, même les pages qui ne sont pas encore en React et qui n'utilisent donc pas le router frontend (React Router).
Ce serait probablement mieux de faire en sorte que le composant TopBar ne s'occupe pas de savoir sur quelle URL on est, mais juste d'accepter une prop qui lui indique si afficher juste le logo ou bien le label de la route.

2021-04-23 14:01 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +  const { pathname } = useLocation();
@giuseppedeponte mais est-ce que c'est un problème d'utiliser useLocation ? Ce hook n'est pas local au routeur, ça importe toute la librairie react-router ? Je trouverai ça bien que la TopBar ne prenne pas de props, parce qu'à terme ce serait bien qu'on essaie de limiter l'effet "refresh de la TopBar" qu'on a quasiment chaque changement de page.

2021-04-23 14:05 UTC, giuseppedeponte commented on agir/front/components/allPages/TopBar/TopBar.js
> +  const { pathname } = useLocation();
useLocation a besoin du context de ReactRouter normalement. 
Personnellement, ça ne m'embête pas que ce soit dans les props, parce que c'est un état du composant TopBar différent (principale / secondaire). En tout cas, je crois que si on veut intégrer la logique de routage ici, ce serait mieux d'avoir deux composants différents, un pour les pages en React et l'autre pour les pages legacy - voir un troisième composant commun qui s'occupe que de l'affichage qu'est commun au deux à priori.

2021-04-23 14:07 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +  const { pathname } = useLocation();
Ok pour les props alors, ça reste le plus simple en effet. Va falloir que je fouille un peu le résultat de react router, je voyais ça plus comme une simple surcouche sur l'API history de navigateur.

2021-04-27 16:14 UTC, jillro requested changes

2021-04-27 16:14 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +          className={path === "/" ? "center grow" : "justify grow"}
alors ça n'aurait pas du y entrer en premier chef, mais on utilise pas les classes CSS

si tu veux des variations de ton styled-components, utilise des props : https://styled-components.com/docs/basics#adapting-based-on-props

2021-04-27 16:14 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +                    <MenuLink href={route[1].path} className="small-only">
pareil

2021-04-27 16:14 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +          <MenuLink href={routes.dashboard} className="large-only">
pareil, même si c'était fait avant, tu peux homogénéiser ?

2021-05-04 08:58 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +        <HorizontalFlex path={path}>
Pour le coup c'est un peu vénère. L'idée n'est pas d'avoir une logique de test dans les styles component, mais une simple logique de paramétrage. Je pense qu'il est plus raisonnable que la logique de test reste en dehors des compostants.

2021-05-04 08:58 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +      : "@media only screen and (max-width: ${+style.collapse - 1}px) {display: none;}"};
duplication :) tu peux mettre ton test juste au niveau de la condition min-width / max-width

2021-05-04 09:13 UTC, Ben-Ji-L commented on agir/front/components/allPages/TopBar/TopBar.js
> +      : "@media only screen and (max-width: ${+style.collapse - 1}px) {display: none;}"};
ah oui mais ça ne fonctionne pas de toute façon

2021-05-04 13:22 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +`;
```suggestion
  (${(small) => small ? "min-width: ${style.collapse}" : "max-width: ${style.collapse - 1}"}px) {
      display-none;
   }
`;
```

2021-05-04 13:26 UTC, jillro reviewed
un exemple de ce que je voulais dire par "garder la logique de test en dehors" :)

2021-05-04 13:26 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +        <HorizontalFlex path={path}>
```suggestion
        <HorizontalFlex center={path === "/"}>
```

2021-05-04 13:26 UTC, jillro commented on agir/front/components/allPages/TopBar/TopBar.js
> +    path === "/" &&
```suggestion
  ${({ center }) =>
    center &&
```

2021-05-04 13:54 UTC, jillro approved these changes

2021-05-04 14:53 UTC, giuseppedeponte commented on agir/front/components/allPages/TopBar/TopBar.js
> +          })()}
Un commentaire, mais pas forcément besoin d'un fix tout de suite : 
cette manière de faire fonctionne, mais par contre n'est pas super optimisée. 
À chaque render du composant une nouvelle fonction est créée et évaluée, même si au final rien ne change dans l'affichage.
Une bonne manière d'optimiser serait déjà de découper cette partie de code et en faire un nouveau composant séparé.
Par exemple : 
```javascript
const TopBarMainLink = props => {
  const { isMobileApp, path } = props;

  if (!isMobileApp) {
    return null;
  }

  if (path === "/") {
    return (
      <MenuLink href={routes.dashboard} small>
        <Logo />
      </MenuLink>
    );
  }

  // route.match et route.getLink fonctionnent normalement 
  // à la fois avec de paths uniques et des arrays

  const currentRoute = routeConfig.find(route => route.match(path));

  if (!currentRoute) {
    return null;
  }
  
  return (
    <MenuLink href={currentRoute.getLink()} small>
      <h1>{currentRoute.label}</h1>
    </MenuLink>
  )
}
```
Découper la logique de cette manière est plus efficace et aussi plus lisible et plus facile à maintenir.
Ça permet par exemple de voir que entre la version avec le logo et la version avec le h1, il n'y a pas tellement de différence, on pourrait même simplifier plus : 
```javascript
const TopBarMainLink = props => {
  const { isMobileApp, path } = props;

  // on met à jour currentRoute uniquement si `path` a changé
  const currentRoute = useMemo(() => {
    return routeConfig.find(route => route.match(path))
  }, [path]);
  
  if (!isMobileApp || !currentRoute) {
    return null;
  }

  return (
    <MenuLink href={currentRoute.getLink()} small>
      {
        currentRoute.id === "dashboard"
          ? <Logo />
          : <h1>{currentRoute.label}</h1>
      }
    </MenuLink>
  )
}
```
Et vu que ce composant est une fonction pure, on pourrait aussi utiliser [`React.memo`](https://fr.reactjs.org/docs/react-api.html#reactmemo) pour limiter encore plus le nombre de render inutiles.

J'espère que c'est clair et ça peut être utile pour la suite. Si tu as des questions n'hésites pas !

2021-05-04 14:55 UTC, giuseppedeponte commented on agir/front/components/allPages/TopBar/TopBar.stories.js
> +    path={useLocation().pathname}
Le router dans le Storybook ne fonctionne pas comme celui de l'app, ça permet juste de pouvoir tester les composants qui ont besoin d'un router sans les faire crasher.
Ici ce serait probablement plus intéressant de définir le `path` dans les arguments du Template, ça permet en plus de pouvoir le modifier dans l'interface de Storybook pour tester directement différents cas de figure.

2021-05-04 14:57 UTC, giuseppedeponte commented on agir/front/components/allPages/TopBar/TopBar.stories.js
> +    path={useLocation().pathname}
Sur cette ligne en particulier : pour éviter les erreurs/confusions, la convention pour les hooks React est de les utiliser en dehors de la valeur renvoyé par la fonction (avant le `return`) et le plus possible tout en haut de la fonction.

2021-05-06 14:10 UTC, giuseppedeponte approved these changes

2021-05-06 14:11 UTC, merged