Component ImageField with preview, error and front-only deletion
lafranceinsoumise/actionpopulaire.fr pull request #541
Opened 2021-04-30 14:58 UTC by maxGoaz

2021-04-30 15:05 UTC, giuseppedeponte requested changes

2021-04-30 15:05 UTC, giuseppedeponte commented on agir/front/components/formComponents/ImageField.js
> +          </>
```suggestion
          <img
            src={thumbnail}
            style={{ width: "178px", height: "100px", marginRight: "1.5rem" }}
          />
```

2021-04-30 15:05 UTC, giuseppedeponte commented on agir/front/components/formComponents/ImageField.js
> +          </>
La taille fixe ne fonctionnera pas avec tous les formats d'image, non ? Ça va les déformer. Il faudrait plutôt essayer avec un maxWidth et un maxHeight.

2021-04-30 15:05 UTC, giuseppedeponte commented on agir/front/components/formComponents/ImageField.js
> +    onDelete,
Plutôt que de faire un onDelete, on peut juste appeler onChange avec null en paramètre, non ?

2021-04-30 15:11 UTC, giuseppedeponte commented on agir/front/components/formComponents/ImageField.js
> +          </>
Ah, non je voulais dire plutôt que, par exemple, une image plus haute que large sera écrasée si on met une largeur et une hauteur fixes

2021-04-30 15:12 UTC, maxGoaz commented on agir/front/components/formComponents/ImageField.js
> +    onDelete,
Pour moi c'est une fonctionnalité différente car le onDelete qui sera passé en props devra faire un call API spécifique pour supprimer l'image contextuelle (ici du groupe) ?

2021-04-30 15:16 UTC, maxGoaz commented on agir/front/components/formComponents/ImageField.js
> +          </>
Je remplace aussi par maxWidth et mawHeight pour un meilleur rendu ;)

2021-04-30 15:34 UTC, giuseppedeponte approved these changes

2021-05-04 08:59 UTC, maxGoaz commented on agir/front/components/formComponents/ImageField.js
> +    onDelete,
J'ai passé ça dans le onChange avec null pour la suppression.

2021-05-04 09:24 UTC, giuseppedeponte approved these changes

2021-05-04 09:43 UTC, merged