Bannière de téléchargement pas si agressive
lafranceinsoumise/actionpopulaire.fr pull request #553
Opened 2021-05-05 16:21 UTC by maxGoaz

/ ! \  Besoin d'ajouter l'annonce custom "**bannerDownload**" dans l'Admin

2021-05-05 16:23 UTC, maxGoaz commented
Manque "Après appui sur la croix, apparaîtra de nouveau après 25 pages", mais non bloquant

2021-05-07 07:57 UTC, giuseppedeponte submitted a review, later dismissed

2021-05-07 13:02 UTC, jillro requested changes

2021-05-07 13:02 UTC, jillro commented on agir/front/components/genericComponents/DownloadApp.js
> +    if (visitCount % 25 === 0) {
Donc là si je le ferme à ma 24ème visite ça se réouvre tout de suite après :) ? 

Idée : quand la personne fermes, tu stockes le compteur de visites actuels + 25. À chaque affichage, tu regardes les compteur de visite, le chiffre stocké pour la bannière : si le compteur est inférieur au chiffre stocké, t'affiches pas, sinon t'affiches.

Et de cette manière, pas besoin de GlobalContext, un simple hook personnalisé avec useLocalStorage de https://github.com/streamich/react-use devrait suffire (on s'est dit qu'on l'ajoutait même si c'est pas encore dans staging).

2021-05-10 10:19 UTC, jillro submitted a review, later dismissed

2021-05-10 10:29 UTC, jillro approved these changes

2021-05-10 10:30 UTC, merged