Contexte ?
lafranceinsoumise/actionpopulaire.fr pull request #619
Opened 2021-05-20 15:28 UTC by jillro

2021-05-20 15:35 UTC, giuseppedeponte requested changes
Deux commentaires, mais sinon c'est parfait pour moi

2021-05-20 15:35 UTC, giuseppedeponte commented on agir/front/components/dashboardComponents/Footer.js
> +                <Link href={routeConfig.login.getLink()}>Se connecter</Link>
Tu peux utiliser Link aussi directement avec la clé de la route :
```suggestion
                <Link route="login">Se connecter</Link>
```

2021-05-20 15:35 UTC, giuseppedeponte commented on agir/front/components/globalContext/nonReactRoutes.config.js
> +  eventMapPage: "/evenements/carte/",
```suggestion
  groupsMap: "/carte/groupes/",
  eventsMap: "/carte/evenements/",
```
Il faudra vérifier s'il reste des endroits où on utilise encore les routes qui venaient du backend, mais ces deux routes sont des page React

2021-05-21 09:34 UTC, maxGoaz commented on agir/events/components/agendaPage/Agenda.js
>              {routes.eventMapPage ? (
Besoin de la condition `(routes.eventMapPage) `  ?

2021-05-21 09:34 UTC, maxGoaz approved these changes

2021-05-21 09:42 UTC, Ben-Ji-L approved these changes

2021-05-21 09:52 UTC, jillro commented on agir/events/components/agendaPage/Agenda.js
>              {routes.eventMapPage ? (
Oui, je crois que si les routes ne sont pas encore chargées dans le contexte ça peut planter, en tout cas elle est présente pour chaque route legacy non react (pour les routes react aucun risque car elles ne viennent pas du contexte), je n'ai pas vérifié si en pratique ça pouvait arriver que le composant s'affiche sans le contexte.

2021-05-21 09:53 UTC, giuseppedeponte approved these changes

2021-05-21 10:46 UTC, merged