Found a 404 ?
lafranceinsoumise/actionpopulaire.fr pull request #628
Opened 2021-05-21 15:05 UTC by maxGoaz

Mettre `DEBUG = False` en local pour pouvoir tester handler404

2021-05-25 08:08 UTC, giuseppedeponte approved these changes

2021-05-25 08:09 UTC, giuseppedeponte approved these changes
Approuvée ! Pour les erreurs dans les tests frontend il devrait suffire juste de mettre la branche à jour avec staging.

2021-05-25 08:20 UTC, Ben-Ji-L approved these changes

2021-05-25 16:35 UTC, giuseppedeponte approved these changes

2021-05-26 08:38 UTC, Ben-Ji-L approved these changes

2021-05-26 15:55 UTC, giuseppedeponte requested changes

2021-05-26 15:55 UTC, giuseppedeponte commented on agir/front/components/notFoundPage/NotFoundPage.js
> +  }
Tu es sûr que la page 404 s'affichera sur la page d'un groupe ou événement si celui-ci n'existe pas ?

Plutôt que de gérer ça ici, il faudrait plutôt transformer ces valeurs en props du composant NotFoundPage, puis sur la page de groupe ou d'événement, utiliser ce composant au cas où les endpoints API renvoient une 404.

2021-05-26 16:20 UTC, jillro commented on agir/front/components/notFoundPage/NotFoundPage.js
> +  }
Effectivement, ça ne suffira pas. Il faudrait effectivement gérer dans les composants groupes et événement que quand on a une erreur 404 on affiche NotFoundPage.

2021-05-26 16:23 UTC, jillro requested changes
Il faudrait remettre le package-lock.json à la version de staging (`$ git checkout staging -- package-lock.json`).

2021-05-27 09:16 UTC, giuseppedeponte commented on agir/front/components/notFoundPage/NotFoundPage.js
>    }
Pourquoi pas juste `title` et `subtitle` ? 
Et pourquoi faire un array au lieu de deux variables ?

2021-05-27 09:41 UTC, maxGoaz commented on agir/front/components/notFoundPage/NotFoundPage.js
>    }
Oui title et subtitle c'est encore mieux :)
Par contre un array n'est pas défini il me semble, ce n'est que la syntaxe pour définir plusieurs variables sur une seule ligne ?

2021-05-27 09:48 UTC, giuseppedeponte commented on agir/front/components/notFoundPage/NotFoundPage.js
>    }
Si, tu définis l'array `["Page", "Cette page"]` et ensuite tu le décomposes pour affecter une valeur aux variables `titleLocation` et `subtitleLocation`

2021-05-27 15:50 UTC, maxGoaz reviewed
Les `PageNotFound` custom s'affiche depuis le front React depuis les retours API des groups et events

2021-05-27 15:50 UTC, jillro commented on agir/events/components/eventPage/EventPage.js
> +        if (error.status === 404) return;
Il ne faut pas non plus retry si c'est 403.

2021-05-27 15:50 UTC, jillro commented on agir/events/components/eventPage/EventPage.js
> +  if (error?.status === 404 || error?.status === 410)
Finalement c'est 403, pas 410 que retourne l'API quand on a pas l'autorisation non ?

2021-05-27 16:24 UTC, giuseppedeponte commented on agir/events/components/eventPage/EventPage.js
> +  if (error?.status === 404 || error?.status === 410)
Normalement 410 est pour les groupes qui existent mais qui ont été dépubliés

2021-05-28 08:07 UTC, giuseppedeponte requested changes

2021-05-28 08:07 UTC, giuseppedeponte commented on agir/events/components/eventPage/EventPage.js
> +    }
Je crois qu'il n'y a pas besoin de surcharger le `fetcher` par défaut. S'il y a une erreur tu peux le récuperer directement dans le retour de `useSWR` :
```suggestion
  const { data: eventData, error } = useSWR(
    api.getEventEndpoint("getEvent", {
      eventPk,
    }),
    {
      onErrorRetry: (error) => {
        if ([404, 410, 403].includes(error.status)) return;
      },
    }
```

2021-05-28 08:07 UTC, giuseppedeponte commented on agir/events/components/eventPage/EventPage.js
> +    }
D'ailleurs, en règle général, c'est mieux d'éviter de définir des fonctions statiques directement dans la fonction du composant car elle sera rédefinie à chaque render : si on n'a pas besoin d’accéder au scope du composant on définit la fonction à l'extérieur, si on a besoin du scope du composant on utilise le hook `useCallback`.

2021-05-28 08:07 UTC, giuseppedeponte commented on agir/groups/components/groupPage/hooks/group.js
> +
```suggestion
```

2021-05-28 08:07 UTC, giuseppedeponte commented on agir/groups/components/groupPage/hooks/group.js
> +  );
```suggestion
  const { data, error } = useSWR(
    api.getGroupPageEndpoint("getGroup", { groupPk }),
    {
      onErrorRetry: (error) => {
        if ([404, 410, 403].includes(error.status)) return;
      },
    }
  );
```

2021-05-28 13:58 UTC, giuseppedeponte approved these changes

2021-05-31 08:18 UTC, giuseppedeponte approved these changes

2021-05-31 08:56 UTC, jillro approved these changes

2021-05-31 08:58 UTC, merged