L'invitation est un devoir, mais le sage doit maintenir ses distances.
lafranceinsoumise/actionpopulaire.fr pull request #639
Opened 2021-05-28 14:32 UTC by Ben-Ji-L

2021-05-28 14:53 UTC, maxGoaz commented on agir/events/components/eventPage/EventHeader.js
> +          )}
Tu auras peut être un espace en trop (à partir des n-ème participant)? 
`(!!guests) && (guests + 1) + "ème"` suffit ?

2021-05-28 15:02 UTC, jillro requested changes

2021-05-28 15:02 UTC, jillro commented on agir/events/components/eventPage/EventHeader.js
> +          {allowGuests && hasSubscriptionForm && (
```suggestion
          {allowGuests && (hasSubscriptionForm || hasPrice) && (
```

2021-05-28 15:04 UTC, maxGoaz approved these changes

2021-05-28 15:52 UTC, jillro approved these changes

2021-05-28 18:44 UTC, jillro approved these changes

2021-05-31 08:15 UTC, giuseppedeponte approved these changes

2021-05-31 08:15 UTC, merged