Ajout des mandats consulaires
lafranceinsoumise/actionpopulaire.fr pull request #644
Opened 2021-05-31 10:25 UTC by aktiur

Les résultats de l'élection des conseillers et délégués consulaires de ce
dimanche dernier seront disponibles ce mardi. Cette PR permettra aux éventuels
gagnants d'indiquer leur nouveau mandat.

Le premier commit met à jour data-france pour ajouter les circonscriptions
consulaires.

Le second commit crée le modèle `MandatConsulaire`, le panneau d'administration
correspondant, ainsi que le formulaire et les vues associées dans le profil
utilisateur.

2021-05-31 11:35 UTC, giuseppedeponte requested changes
C'est ok, mais on a un autre formulaire maintenant avec une sélection possible du mandat ici : `agir/front/components/authentication/Connexion/TellMore/TellMore.js:103`

2021-05-31 12:36 UTC, jillro commented
De même façon, est-ce que le nouveau type de mandat est géré dans l'API de telle sorte à ce qu'on puisse le mettre dans les formulaires d'inscription Wordpress ?

2021-05-31 15:04 UTC, aktiur commented
@giuseppedeponte j'ai ajouté le types de mandat consulaire dans `MANDAT_OPTIONS` dans `TellMore.js`, et d'après ce que j'ai vu, le champ `PersonMandatField` utilisé par le serializer à l'autre bout récupère les valeurs légales depuis le `types_elus` qui comporte bien la valeur `"consulaire"`. Mais je constate que du coup ce champ de serializer ne semble donc pas accepter la valeur `"maire"`, qui n'est pas un type d'élus différent, et qui devrait être traitée spécialement dans ce serializer.

@jillro J'ai ajouté le traitement de ce type de mandat dans le serializer de l'API de souscription utilisée par le formulaire wordpress

2021-05-31 15:21 UTC, giuseppedeponte commented
@aktiur Il me semble qu'on avait justement supprimé le choix `maire` de ce formulaire pour simplifier le serializer, vu que ce type n'était plus dans `types_elus`. Tu penses qu'il peut y avoir un bug à cet endroit ?

2021-05-31 19:32 UTC, aktiur commented
@giuseppedeponte effectivement il est plus proposé côté front non plus, du coup y a du code mort dans `agir.people.serializers.PersonMandatField` (que je n'ai pas modifié dans cette PR)

2021-05-31 21:06 UTC, jillro approved these changes

2021-06-01 08:06 UTC, giuseppedeponte approved these changes

2021-06-01 09:15 UTC, maxGoaz approved these changes

2021-06-01 09:18 UTC, merged