STOP PUB
lafranceinsoumise/actionpopulaire.fr pull request #670
Opened 2021-06-08 15:46 UTC by maxGoaz

2021-06-08 16:01 UTC, giuseppedeponte commented on agir/activity/components/NotificationSettings/NotificationSettingItem.js
> +      {notification.hasPush !== false ? (
Tu peux faire directement : 
```
<StyledButton
          $active={push}
          $hidden={notification.hasPush === false}
          aria-label={
            push ? "Désactiver la notification" : "Activer la notification"
          }
          onClick={togglePush}
          disabled={disabled}
        >
          <RawFeatherIcon width="1.25rem" height="1.25rem" name="bell" />
        </StyledButton>
```
Et pareil pour l'autre bouton.

2021-06-08 16:03 UTC, giuseppedeponte commented on agir/activity/components/NotificationSettings/NotificationSettingPanel.js
> +                    <small>E-mail</small>
Tu affiches le titre de la colonne même s'il n'y a pas de boutons en dessous ?

2021-06-09 08:55 UTC, maxGoaz commented on agir/activity/components/NotificationSettings/NotificationSettingPanel.js
> +                    <small>E-mail</small>
En l'état ces titres de colonnes étaient affichés seulement pour le premier `sous-type` de chaque `type` de notification.
La condition d'affichage est bien de vérifier si il y aura des boutons correspondants mais cela ne fonctionne pas pour les boutons du type entier (soit les sous-types suivants le premier)
En gros le premier sous type décide l'affichage du titre pour l'ensemble des sous types qui comportent peut être des boutons.

De mon côté maintenant ça marche car avec les notif mails qui vont être rajoutées il y aura toujours au moins un bouton de chaque titre notif/email. Mais pour que ça fonctionne tout le temps il faudra refaire une condition plus générale sur tous les sous-titres effectivement ! :)

2021-06-09 09:11 UTC, giuseppedeponte commented on agir/activity/components/NotificationSettings/NotificationSettingPanel.js
> +                    <small>E-mail</small>
Ok, si de toute façon il y a toujours un sous-type avec les deux boutons on peut toujours afficher les deux titres.

2021-06-14 15:04 UTC, giuseppedeponte commented on agir/front/components/allPages/TopBar/UserMenu.js
> +            route={routeSettings}
La valeur de `route` normalement devrait être un string correspondant à l'id de la route dans routeConfig, par ex. ici tu peux faire `route="notificationSettings"`. Sinon, pour passer un URL tu peux utiliser `href` (pour les liens externes) ou `to` pour les liens de React router.

2021-06-15 15:08 UTC, maxGoaz commented on agir/lib/templates/mail_templates/NEW_MESSAGE.html
> +        <table class="vb-container fullpad" style="border-collapse: separate; border-spacing: 18px; padding-left: 0; padding-right: 0; width: 100%; max-width: 570px; background-color: #EEEEEE;" width
Oui c'est une demande d'Agathe :)

2021-06-15 15:09 UTC, maxGoaz commented on agir/donations/tasks.py
> +
Hmm tu as gardé les commentaires de l'autre fois ?
Certains commentaires font part de code qui n'existe plus sur ma branche

2021-06-15 15:10 UTC, maxGoaz commented on agir/donations/tasks.py
> +from ..activity.models import Activity
Je n'ai plus ce code non plus de mon côté, je ne sais pas si ta review concerne la dernière version

2021-06-15 16:10 UTC, maxGoaz commented on agir/events/forms.py
> +                        status=Activity.STATUS_UNDISPLAYED,
J'ai rajouté la ligne

2021-06-15 16:15 UTC, maxGoaz commented on agir/people/migrations/0005_add_subscriptions.py
> +            for p in Person.objects.all().filter(event_notifications=True)
J'avoue j'avais pas pensé à l'impact sur le moment, je regarde comment optimiser ça :D

2021-06-16 15:45 UTC, giuseppedeponte requested changes

2021-06-16 15:45 UTC, giuseppedeponte commented on agir/people/forms/subscription.py
>              person.subscribed = False
Il faudrait supprimer les souscriptions éventuelles ici, non ?

2021-06-16 15:48 UTC, jillro commented on agir/people/forms/subscription.py
>              person.subscribed = False
Oui, si les gens ne veulent plus recevoir des news il faut les désabonner des notifs aussi.

2021-06-16 15:50 UTC, jillro commented
On a encore un soucis : en modifiant la liste `DEFAULT_PERSON_SUBSCRIPTION_ACTIVITY_TYPES`, on modifie aussi les souscription aux push qui sont crééent par défaut, et on casse l'existant. Ceci dit, c'est probablement la manière dont fonctionnent les push obligatoire qui n'est pas la bonne.

Il faudrait probablement, pour les emails comme pour les push, une liste de type mandatory, et une liste de type paramétrables. Pour les push, on pourrait utiliser cette liste de type mandatory directement à la gestion de l'envoi des push, et ne créer des subscription que pour les paramétrables. Ton avis @giuseppedeponte aussi ?

2021-06-16 15:56 UTC, giuseppedeponte commented
> On a encore un soucis : en modifiant la liste `DEFAULT_PERSON_SUBSCRIPTION_ACTIVITY_TYPES`, on modifie aussi les souscription aux push qui sont créés par défaut, et on casse l'existant. Ceci dit, c'est probablement la manière dont fonctionnent les push obligatoire qui n'est pas la bonne.
> 
> Il faudrait probablement, pour les emails comme pour les push, une liste de type mandatory, et une liste de type paramétrables. Pour les push, on pourrait utiliser cette liste de type mandatory directement à la gestion de l'envoi des push, et ne créer des subscription que pour les paramétrables. Ton avis @giuseppedeponte aussi ?

Oui, tout à fait d'accord pour ne pas créer de souscription en base de données pour celles qui sont obligatoires. Mais on aura toujours besoin d'une liste de notifications non obligatoires qu'on veut activer par défaut, non ?

2021-06-16 16:04 UTC, jillro commented
> > On a encore un soucis : en modifiant la liste `DEFAULT_PERSON_SUBSCRIPTION_ACTIVITY_TYPES`, on modifie aussi les souscription aux push qui sont créés par défaut, et on casse l'existant. Ceci dit, c'est probablement la manière dont fonctionnent les push obligatoire qui n'est pas la bonne.
> > Il faudrait probablement, pour les emails comme pour les push, une liste de type mandatory, et une liste de type paramétrables. Pour les push, on pourrait utiliser cette liste de type mandatory directement à la gestion de l'envoi des push, et ne créer des subscription que pour les paramétrables. Ton avis @giuseppedeponte aussi ?
> 
> Oui, tout à fait d'accord pour ne pas créer de souscription en base de données pour celles qui sont obligatoires. Mais on aura toujours besoin d'une liste de notifications non obligatoires qu'on veut activer par défaut, non ?

Oui absolument. Mais là la liste des types obligatoires n'est pas listée. Il faudrait qu'elle le soit comme la liste par défaut, comme single truth of knowledge.

2021-06-16 16:21 UTC, maxGoaz commented
Pour l'instant je crois que les notifications obligatoires sont les mêmes entre les push et emails ?
Si elles ne sont pas les mêmes il faut en effet les distinguer.
Par contre si ce sont toujours les mêmes types qui sont obligatoires pour les push et emails, je pense que l'on pourrait directement supprimer les notifs obligatoires des types par défaut (= types paramétrables).

2021-06-17 08:21 UTC, jillro commented on agir/people/forms/subscription.py
> +                s.delete()
```suggestion
        Subscription.objects.filter(
            type=Activity.SUBSCRIPTION_EMAIL, person=person
        ).delete()
```

2021-06-28 11:40 UTC, merged