add right margin to the navbar butons on smalls desktops
lafranceinsoumise/actionpopulaire.fr pull request #712
Opened 2021-06-16 14:44 UTC by Ben-Ji-L

2021-06-16 15:27 UTC, giuseppedeponte requested changes

2021-06-16 15:27 UTC, giuseppedeponte commented on agir/front/components/allPages/TopBar/TopBar.js
> +`;
En faisant comme ça on perd l'animation au chargement.
Par contre normalement tu peux ajouter des styles au composant PageFadeIn comme ça :
```jsx
import PageFadeIn from "@agir/front/genericComponents/PageFadeIn";
// ...   
const StyledPageFadeIn = styled(PageFadeIn)`
  & > div {
    margin-right: 1rem;
  }
`;
// ...   
<StyledPageFadeIn ready={isSessionLoaded}>
{/* ... */ }
</StyledPageFadeIn>
```

2021-06-16 15:47 UTC, maxGoaz approved these changes

2021-06-16 16:00 UTC, jillro approved these changes

2021-06-21 07:56 UTC, giuseppedeponte approved these changes

2021-06-21 07:56 UTC, merged