STOP PUB : fixes V2
lafranceinsoumise/actionpopulaire.fr pull request #744
Opened 2021-06-28 16:09 UTC by maxGoaz

2021-06-28 16:24 UTC, giuseppedeponte requested changes

2021-06-28 16:24 UTC, giuseppedeponte commented on agir/notifications/components/common/notifications.config.js
> +    hasEmail: false,
Laisser à `true`, même si pour l'instant il n'y a pas encore d'email associé

2021-06-29 08:09 UTC, giuseppedeponte approved these changes

2021-06-29 08:28 UTC, jillro approved these changes

2021-06-29 08:33 UTC, merged