Wording subtitle panel notifications
lafranceinsoumise/actionpopulaire.fr pull request #797
Opened 2021-07-02 12:27 UTC by maxGoaz

2021-07-02 12:46 UTC, jillro approved these changes

2021-07-02 14:17 UTC, giuseppedeponte commented on agir/activity/components/NotificationSettings/NotificationSettingPanel.js
> +        <InlineBlock>sur votre téléphone.</InlineBlock>
Il n'y a plus besoin de l'espace ?

2021-07-02 15:41 UTC, giuseppedeponte requested changes
Juste un espace à ajouter

2021-07-05 08:28 UTC, maxGoaz commented on agir/activity/components/NotificationSettings/NotificationSettingPanel.js
> +        <InlineBlock>sur votre téléphone.</InlineBlock>
Bien vu je modifie

2021-07-05 08:33 UTC, giuseppedeponte approved these changes

2021-07-05 08:36 UTC, merged