create people admin filter to select people who animate multiple groups
lafranceinsoumise/actionpopulaire.fr pull request #807
Opened 2021-07-06 08:37 UTC by Ben-Ji-L

2021-07-06 09:34 UTC, giuseppedeponte requested changes

2021-07-06 09:34 UTC, giuseppedeponte commented on agir/people/models.py
> +        return anime
C'est probablement plus rapide de faire directement le compte dans la requête, au lieu de faire un boucle :
```suggestion
    @property
    def number_of_groups_animated(self):
        return SupportGroup.objects.filter(
            memberships__person=self,
            memberships__membership_type__gte=Membership.MEMBERSHIP_TYPE_MANAGER,
        ).count()
```
(il faudra juste ajouter l'import de `Membership`)

2021-07-06 10:09 UTC, giuseppedeponte approved these changes

2021-07-06 11:56 UTC, jillro commented on agir/people/admin/panels.py
> +            for p in queryset:
Une petite boucle sur un millier de lignes ? Le serveur va adorer ^^

Petite piste avec les annotations et les aggrégations pour effectuer toutes ces opérations en base de donnée :
```suggestion
            return queryset.annotate(animated_groups=Count("memberships", filter=Q(membership__membership_type__gte=Membership.MEMBERSHIP_TYPE_MANAGER)).filter(animated_groups__gt=1)
```

À adapter et préciser probablement, plus de doc ici : https://docs.djangoproject.com/fr/3.2/topics/db/aggregation/

2021-07-06 11:57 UTC, jillro reviewed
Il ne peut pas y avoir de boucle dans un tel filtre.

2021-07-06 13:43 UTC, jillro commented
Black ne passe pas :)

2021-07-06 15:52 UTC, jillro requested changes

2021-07-06 15:52 UTC, jillro commented on agir/people/models.py
> +        ).count()
Du coup c'est plus nécessaire, dans un soucis de légèreté ce serait bien de l'enlever et pour ne pas introduire une propriété qui est juste utilisée dans les tests.

2021-07-07 08:35 UTC, jillro commented on agir/people/models.py
> +from ..groups.models import SupportGroup, Membership
```suggestion
```

2021-07-07 08:35 UTC, jillro commented on agir/people/tests/test_models.py
> +from agir.groups.models import SupportGroup, Membership
```suggestion
```

2021-07-07 08:35 UTC, jillro requested changes
Finalement tu as supprimé les tests ?

2021-07-07 13:48 UTC, jillro approved these changes

2021-07-07 13:53 UTC, merged