Create Event thumbnail for social media
lafranceinsoumise/actionpopulaire.fr pull request #824
Opened 2021-07-07 09:55 UTC by Ben-Ji-L

2021-07-07 10:18 UTC, giuseppedeponte commented on agir/events/urls.py
> +    path("evenemets/<uuid:pk>/og-image/", views.EventThumbnailView.as_view(), name="view_og_image_event"),
```suggestion
    path("evenements/<uuid:pk>/og-image/", views.EventThumbnailView.as_view(), name="view_og_image_event"),
```

2021-07-19 15:07 UTC, giuseppedeponte approved these changes

2021-07-20 15:00 UTC, maxGoaz requested changes

2021-07-20 15:00 UTC, maxGoaz commented on agir/events/views/event_views.py
> +            )
Il serait peut-être plus lisible de définir une fonction pour assigner `font` avec en argument `size` puisque le reste est toujours pareil ?

```
def getImageFont(size):
  return font = ImageFont.truetype(
                "poppins.ttf",
                size=size,
                encoding="utf-8",
                layout_engine=ImageFont.LAYOUT_BASIC,
            )
font = getImageFont(27)
```

2021-07-20 15:00 UTC, maxGoaz commented on agir/events/views/event_views.py
> +        elif len(self.event.name) < 74:
On pourrait aussi faire un `switch case` vu le nombre de conditions mais après c'est une question de préférence :)

2021-07-20 15:43 UTC, Ben-Ji-L commented on agir/events/views/event_views.py
> +        elif len(self.event.name) < 74:
pour l'instant, je n'ai pas vu de moyens simples pour faire un switch comme dans les autres langages.

2021-07-21 09:20 UTC, maxGoaz commented on agir/events/views/event_views.py
> +        elif len(self.event.name) < 74:
En effet je pensais qu'il existait !

2021-07-21 09:21 UTC, maxGoaz approved these changes

2021-07-21 15:54 UTC, jillro requested changes
Il n'y a plus qu'à changer l'URL utilisée par ObjectOpenGraphMixin dans EventDetailView pour que le code soit effectivement utilisé !

2021-07-23 10:21 UTC, giuseppedeponte approved these changes
Il faut juste mettre à jour la branche et résoudre le conflit

2021-07-23 13:14 UTC, maxGoaz commented on agir/events/views/event_views.py
> +            )
Appeler la fonction générique ?

2021-07-23 13:14 UTC, maxGoaz commented on agir/events/views/event_views.py
> +            )
ici aussi ?

2021-07-23 13:15 UTC, maxGoaz reviewed
Petits changements ?

2021-07-23 13:23 UTC, merged