Feat: panel event management
lafranceinsoumise/actionpopulaire.fr pull request #878
Opened 2021-07-20 15:35 UTC by maxGoaz

2021-08-24 13:00 UTC, giuseppedeponte commented on agir/events/components/EventSettings/EventParticipants.js
> +      }) || [],
Voir le commentaire plus haut

2021-08-24 13:00 UTC, giuseppedeponte commented on agir/events/components/EventSettings/EventParticipants.js
> +          </StyledLink> */}
```suggestion
```

2021-08-24 13:03 UTC, giuseppedeponte commented on agir/events/components/EventSettings/EventVisio.js
> +    const res = await api.updateEvent(eventPk, { online_url: onlineUrl });
Pourquoi pas `onlineUrl` ?

2021-08-24 13:04 UTC, giuseppedeponte commented on agir/events/components/EventSettings/EventVisio.js
> +      </Button>
```suggestion
      <Button
        color="secondary"
        wrap
        disabled={isLoading}
        type="submit"
      >
        Enregistrer
      </Button>
```
Ajouter un formulaire avec une prop `onSubmit` plutôt

2021-08-24 13:11 UTC, giuseppedeponte commented on agir/events/components/createEventPage/EventForm/DateField.js
> +  }, [startTime]);
Il y a besoin de faire tout ça ? Normalement ce champs fonctionnait avant sans être obligé d'écrire en dur dans le code les options de durée (elles étaient juste dans une constante avant).

2021-08-24 13:14 UTC, giuseppedeponte commented on agir/events/components/createEventPage/EventForm/OnlineUrlField.js
> +  const [onlineUrl, setOnlineUrl] = useState(value);
Pourquoi dupliquer la valeur dans un state ?

2021-08-24 13:17 UTC, giuseppedeponte commented on agir/events/components/eventPage/EventHeader.js
> +              href={isDesktop ? routes.manage : routes.manageMobile}
Il y a vraiment besoin de faire deux routes différentes pour mobile et desktop ?

2021-08-24 13:23 UTC, giuseppedeponte commented on agir/events/serializers.py
> +    organizers = serializers.SerializerMethodField()
Pas besoin de les ajouter ici si tu ne les utilise pas. Tu peux les définir directement dans EventAdvancedSerializer

2021-08-24 13:28 UTC, giuseppedeponte commented on agir/events/serializers.py
> +        ).data
Si tu as besoin uniquement de ces informations, c'est mieux pour les performances de ne pas utiliser le PersonSerializer, mais de renvoyer directement des dictionnaires :
```suggestion
def get_participants(self, obj):
    return [
        {
            "id": person.id,
            "email": person.email,
            "firstName": person.first_name,
            "lastName": person.last_name,
            "displayName": person.display_name
        }
        for person in obj.attendees
    ]

def get_organizers(self, obj):
    return [
        {
            "id": person.id,
            "email": person.email,
            "firstName": person.first_name,
            "lastName": person.last_name,
            "displayName": person.display_name
        }
        for person in obj.organizers
    ]
```
Et d'ailleurs tu es sûr d'avoir besoin aussi de firstname et lastname ?

2021-08-24 13:29 UTC, giuseppedeponte commented on agir/events/urls.py
> +        views.CreateOrganizerConfigView.as_view(),
```suggestion
        views.CreateOrganizerConfigAPIView.as_view(),
```

2021-08-24 13:29 UTC, giuseppedeponte commented on agir/events/views/api_views.py
> +    "CreateOrganizerConfigView",
```suggestion
    "CreateOrganizerConfigAPIView",
```

2021-08-24 13:29 UTC, giuseppedeponte commented on agir/events/views/api_views.py
> +class CreateOrganizerConfigView(APIView):
```suggestion
class CreateOrganizerConfigAPIView(APIView):
```

2021-08-24 13:34 UTC, giuseppedeponte commented on agir/events/views/api_views.py
> +            )
C'est plutôt une erreur de validation, qu'un 500 :
https://www.django-rest-framework.org/api-guide/exceptions/#validationerror
Et sinon il y a probablement moyen d'utiliser la classe CreateAPIView de rest framework avec un serializer dédié plutôt que de récrire toute la méthode post

2021-08-24 13:35 UTC, giuseppedeponte commented on agir/events/views/event_views.py
>  class CancelEventView(BaseEventAdminView, DetailView):
On peut utiliser une view rest framework, non ?

2021-08-24 13:37 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
> +            <br />A remplir à la fin de l'événement
Si on veut garder ce composant générique, il faudrait que ce texte soit dynamique

2021-08-24 13:38 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
> +      {!!subtitle && <h6>{subtitle}</h6>}
Il n'y pas besoin normalement de vérifier - il y a même une règle CSS qui cache le h6 s'il est vide

2021-08-24 13:38 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
> +              <ManagementMenuItem item={item} disabled={item.isPending} />
Pourquoi `item.isPending`, plutôt que `item.isDisabled` ou `item.disabled` ?

2021-08-24 13:39 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
> +                  <ManagementMenuItem item={item} cancel={true} />
```suggestion
                  <ManagementMenuItem item={item} cancel />
```

2021-08-24 13:40 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ObjectManagement.js
> +  // }
Ça ne casse rien de commenter ce code ?.

2021-08-24 13:41 UTC, giuseppedeponte commented on agir/front/urls.py
> +    # path("evenements/<uuid:pk>/", views.EventDetailView.as_view(), name="view_event"),
```suggestion
```

2021-08-24 13:43 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupContactPage.js
> +import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents.js";
```suggestion
import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents";
```

2021-08-24 13:43 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupFinancePage.js
> +import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents.js";
```suggestion
import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents";
```

2021-08-24 13:44 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupGeneralPage.js
> +import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents.js";
```suggestion
import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents";
```

2021-08-24 13:44 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupLinksPage.js
> +import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents.js";
```suggestion
import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents";
```

2021-08-24 13:44 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupLocalizationPage.js
> +import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents.js";
```suggestion
import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents";
```

2021-08-24 13:44 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupManagementPage/EditionPanel.js
> +import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents.js";
```suggestion
import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents";
```

2021-08-24 13:45 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupMaterielPage.js
> +import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents.js";
```suggestion
import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents";
```

2021-08-24 13:45 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupMemberPage.js
> +import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents.js";
```suggestion
import { StyledTitle } from "@agir/front/genericComponents/ObjectManagement/styledComponents";
```

2021-08-24 13:48 UTC, maxGoaz commented on agir/events/components/EventSettings/EventFeedback.js
> +      compteRenduPhotos:
On veut pouvoir ajouter plusieurs photos normalement, mais j'attendais le design d'Agathe

2021-08-24 14:35 UTC, maxGoaz commented on agir/events/components/EventSettings/EventOrganization.js
> +      }) || [],
Il n'y a pas de mutation là si ?

Oui du coup c'est encore plus concis en retournant l'objet :)
 
```suggestion
      event?.organizers?.map((organizer) => ({...organizer, memberType: 1})) || [],
```

2021-08-24 14:37 UTC, giuseppedeponte commented on agir/events/components/EventSettings/EventOrganization.js
> +      }) || [],
Oui, mais ce serait vraiment mieux si on faisait sans ajouter la propriété memberType

2021-08-24 14:42 UTC, maxGoaz commented on agir/events/components/createEventPage/EventForm/DateField.js
> +  }, [startTime]);
En fait ce champs de sélection de durée fonctionnait déjà bien avant à la création d'évènement.
Seulement le composant doit maintenant afficher la durée en fonction de celle qui a été enregistrée, d'où le calcul par rapport aux dates de début et de fin pour retrouver l'affichage s'il n'est pas personnalisé.

2021-08-24 14:47 UTC, maxGoaz commented on agir/events/components/eventPage/EventHeader.js
> +              href={isDesktop ? routes.manage : routes.manageMobile}
Alors en fait l'accès au panneau de gestion de groupe n'est pas le même que celui de gestion d'évènement.
Pour les groupes : on accède via des liens du menu sur desktop (membres, etc) et à la racine du menu sur mobile.
Pour les évènements : actuellement il n'y a qu'un bouton pour ouvrir le panneau, or sur desktop on veut afficher directement le premier lien du menu.

Après cela n'empêche pas d'atteindre le résultat d'une autre manière !

2021-08-24 14:48 UTC, giuseppedeponte commented on agir/events/components/createEventPage/EventForm/DateField.js
> +  }, [startTime]);
Et ça suffit pas juste de voir si la différence en minutes entre endTime et startTime est égale à une des options de durée ?

2021-08-24 15:24 UTC, maxGoaz commented on agir/events/components/createEventPage/EventForm/DateField.js
> +  }, [startTime]);
Oui c'est vrai que ça marche aussi ! J'ai fait les changements pour là

2021-08-24 15:45 UTC, maxGoaz commented on agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
> +      {!!subtitle && <h6>{subtitle}</h6>}
D'acc je savais pas ! :)

2021-08-24 15:49 UTC, maxGoaz commented on agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
> +              <ManagementMenuItem item={item} disabled={item.isPending} />
Pour moi cela évoque que la variable est amenée à changer dans le temps.
La fonction n'est d'ailleurs pas encore créée !

2021-08-24 15:52 UTC, maxGoaz commented on agir/front/components/genericComponents/ObjectManagement/ObjectManagement.js
> +  // }
Ca m'empêchait et m'empêche toujours d'ouvrir le panneau, j'ai l'impression que cela ne casse rien. Je l'enlève ?

2021-08-24 15:56 UTC, giuseppedeponte commented on agir/events/components/eventPage/EventHeader.js
> +              href={isDesktop ? routes.manage : routes.manageMobile}
Oui, il me semble que pour les groupes on utilise les même routes, mais sur desktop on redirige automatiquement sur la première route de sous-menu si on arrive sur celle du menu principale

2021-08-24 15:57 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
> +              <ManagementMenuItem item={item} disabled={item.isPending} />
ok, alors pourquoi pas isPending={item.isPending} ?

2021-08-24 15:57 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ObjectManagement.js
> +  // }
Normalement on s'en sert pour ne pas ouvrir le menu sur la page de groupe si l'utilsateur n'as pas les droits de gestion du groupe

2021-08-24 15:58 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ObjectManagement.js
> +  // }
-agir/groups/components/groupPage/GroupSettings/index.js:19-30

2021-09-01 10:24 UTC, jillro commented
Je ferai une review finale après vos retours ensemble, je vous laisse me taguer quand c'est bon.

2021-09-01 14:20 UTC, maxGoaz commented on agir/events/components/eventPage/EventHeader.js
> +              href={isDesktop ? routes.manage : routes.manageMobile}
Ce n'est pas le cas en l'état quand on clique sur "Gestion" depuis "Mes groupes".
Je regarde comment faire

2021-09-02 13:07 UTC, giuseppedeponte requested changes

2021-09-02 13:07 UTC, giuseppedeponte commented on agir/events/views/api_views.py
> +        event.save()
Attention, si tu écrase la methode post, il faut aussi penser à vérifier les permissions. 
```
class CancelEventPermissions(GlobalOrObjectPermissions):
    perms_map = {
        "POST": [],
    }
    object_perms_map = {
        "POST": ["events.change_event"],
    }


class CancelEventAPIView(GenericAPIView):
    permission_classes = (CancelEventPermissions,)
    queryset = Event.objects.all()

    def post(self, request, pk):
        event = self.get_object()
        event.visibility = Event.VISIBILITY_ADMIN
        event.save()

        send_cancellation_notification.delay(pk)

        return JsonResponse(
            {"data": _("L'événement « {} » a bien été annulé.").format(event.name)}
        )
```

2021-09-02 13:07 UTC, giuseppedeponte commented on agir/events/views/api_views.py
> +        event.save()
Et il faudrait peut-être empêcher d'annuler un événement passé ?

2021-09-02 13:07 UTC, giuseppedeponte commented on agir/events/urls.py
>          "evenements/<uuid:pk>/annuler/",
```suggestion
        "api/evenements/<uuid:pk>/annuler/",
```

2021-09-02 13:07 UTC, giuseppedeponte commented on agir/events/urls.py
>          "evenements/<uuid:pk>/annuler/",
Et peut-être déplacer cette définition un peu plus bas, avec les autres endpoints API

2021-09-02 13:07 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ObjectManagement/ManagementMenu.js
> +  const { items, title, subtitle, onBack, cancel, isFinished } = props;
```suggestion
  const { items, title, subtitle, onBack, cancel, isPast } = props;
```

2021-09-02 13:07 UTC, giuseppedeponte commented on agir/groups/components/groupComponents/GroupCard.js
> +  const isDesktop = useIsDesktop();
Ce n'est pas utilisé, non ? Et `groupRouteConfig` non plus ?

2021-09-02 13:07 UTC, giuseppedeponte commented on agir/groups/components/groupPage/GroupSettings/GroupSettings.js
> +
```suggestion
  // Open first panel on Desktop
  if (isDesktop && pathname.substr(-8) === "gestion/") {
    return <Redirect to={"membres/"} />;
  }
```

2021-09-03 12:21 UTC, maxGoaz commented on agir/events/components/EventSettings/routes.config.js
> +    canDisabled: true,
Ici c'est pour signifier que l'élément "peut" être désactivé, pas qu'il le soit. 
Sémantiquement tu mettrais quand même `isDisabled ` ?

2021-09-03 12:33 UTC, giuseppedeponte commented on agir/events/components/EventSettings/routes.config.js
> +    canDisabled: true,
`isDisabled` = est désactivé
`canDisable` = peut désactiver
Ça veut dire quoi que la route peut-être désactivée ? Par qui ?

2021-09-03 13:14 UTC, maxGoaz commented on agir/events/components/createEventPage/EventForm/OnlineUrlField.js
> +    setIsAuto(true);
`isAuto` permet de cocher/décocher "activer le service de visio automatique de LFI"
Sans cet état, il reste coché et cela donne l'impression à l'utilisateur de n'être plus libre de modifier l'url.
Mais ce ressenti est plutôt personnel :)

2021-09-03 13:26 UTC, maxGoaz commented on agir/events/serializers.py
> +                "memberType": 1,
A la base j'avais rajouté cette propriété uniquement côté front pour les organisateurs : c'est pour afficher leur statut dans le composant EventMember (comme pour les référents des composants des groupMember).
Je pensais dans ton commentaire que tu proposais de l'ajouter directement via le BackEnd ?
Je vais opter pour `isOrganizer` en tout cas ;)

2021-09-03 13:40 UTC, maxGoaz commented on agir/groups/components/groupComponents/GroupCard.js
> +  const isDesktop = useIsDesktop();
En effet j'avais oublié de retirer ça après le refactor !

2021-09-03 15:13 UTC, maxGoaz commented on agir/events/views/api_views.py
> +        event.save()
Normalement les permissions sont là pour la méthode POST dans `EventManagementPermissions` ?
On ne veut pas pouvoir supprimer un événement passé ?

2021-09-03 15:26 UTC, giuseppedeponte commented on agir/events/views/api_views.py
> +        event.save()
> Normalement les permissions sont là pour la méthode POST dans EventManagementPermissions ?
Le permissions sont définies dans `EventManagementPermissions`, mais elles ne sont jamais utilisées - il faut appeler la methode `get_object` ou `check_object_permission` pour que la vérification se fasse. 

>  On ne veut pas pouvoir supprimer un événement passé ?
Je ne sais pas si on a décidé autrement, mais en tout cas aujourd'hui on ne peut annuler que les événements à venir (cf. https://github.com/lafranceinsoumise/actionpopulaire.fr/blob/7020b88f3f7e705387735a9280eae0915e7626ce/agir/events/views/event_views.py#L607)

2021-09-03 16:17 UTC, maxGoaz commented on agir/events/components/EventSettings/routes.config.js
> +    canDisabled: true,
Alors c'est pas la route qui peut être désactivée mais l'item du menu (ici les Compte rendus) qui est désactivé si l'évènement n'est pas terminé.
Donc la désactivation est variable en fonction de la date

2021-09-06 08:29 UTC, maxGoaz commented on agir/events/components/EventSettings/routes.config.js
> +    canDisabled: true,
Alors c'est pas la route qui peut être désactivée mais l'item du menu (ici les Compte rendus) qui est désactivé si l'évènement n'est pas terminé.
Donc la désactivation est variable en fonction de la date

2021-09-06 09:19 UTC, giuseppedeponte commented on agir/events/components/EventSettings/routes.config.js
> +    canDisabled: true,
Ok, je comprends, mais je crois que ce serait mieux d'expliciter ça encore plus dans la config en appelant la propriété `forPastEventsOnly`/`forUpcomingEventsOnly` ou quelque chose comme ça

2021-09-06 11:15 UTC, giuseppedeponte requested changes

2021-09-06 11:15 UTC, giuseppedeponte commented on agir/events/components/eventPage/EventHeader.js
> +import { menuRoute } from "@agir/events/EventSettings/routes.config";
Ce serait mieux d'utiliser la route `eventSettings` dans la config des routes de l'app et en l'appellant avec la methode `getLink` :
```js
import { routeConfig } from "@agir/front/app/routes.config";
// ...
<Button icon="settings" link to={routeConfig.eventSettings.getLink({ eventPk: event.id })} color="primary">
```

2021-09-06 11:15 UTC, giuseppedeponte commented on agir/events/views/api_views.py
> +
```suggestion
        self.get_object()
```
Je crois que `get_object` appelle aussi `check_object_permissions`, normalement il n'y a pas besoin de le rappeler (et il n'y pas besoin de l'enregistrer dans `self.object` non plus)

2021-09-06 12:56 UTC, giuseppedeponte approved these changes

2021-09-08 11:18 UTC, jillro approved these changes

2021-09-08 11:18 UTC, jillro commented on agir/events/components/common/api.js
> +          ? { image: "La taille du fichier ne doit pas dépasser le 2.5 Mo" }
```suggestion
          ? { image: "La taille du fichier ne doit pas dépasser 2.5 Mo" }
```

2021-09-08 11:24 UTC, merged