Refactor button styles
lafranceinsoumise/actionpopulaire.fr pull request #885
Opened 2021-07-22 13:48 UTC by giuseppedeponte

2021-07-23 09:11 UTC, maxGoaz requested changes

2021-07-23 09:11 UTC, maxGoaz commented on agir/events/components/eventRequiredDocuments/EventRequiredDocuments.js
> +              Voir tout&ensp;
C'était plutôt pour remplacer par `&nbsp;` non ?

2021-07-23 09:11 UTC, maxGoaz commented on agir/front/components/authentication/Connexion/Code/CodeLogin.js
> +            style={{ width: "100%", height: 40 }}
La props `$block` ne suffit pas pour mettre à 100% ?

2021-07-23 09:11 UTC, maxGoaz commented on agir/front/components/toolsPage/ToolsPage.js
> +    Accéder au site matériel&ensp;
&nbsp; ici aussi ?

2021-07-23 09:11 UTC, maxGoaz commented on agir/front/components/toolsPage/ToolsPage.js
> +      Accéder au centre d'aide&ensp;
là encore

2021-07-23 12:20 UTC, maxGoaz approved these changes

2021-08-10 15:13 UTC, jillro commented on agir/front/components/genericComponents/Button/BaseButton.js
> +      ["link", "small", "block", "wrap"].includes(prop) === false,
Ohhh je découvre ça, excellent !

2021-08-10 15:13 UTC, jillro commented on agir/front/components/notFoundPage/NotFoundPage.js
> +      12
Je crois que c'est une typo ?

2021-08-23 08:43 UTC, jillro approved these changes

2021-08-23 08:43 UTC, merged