create open graph image for support groups
lafranceinsoumise/actionpopulaire.fr pull request #894
Opened 2021-07-27 14:08 UTC by Ben-Ji-L

2021-07-27 15:44 UTC, giuseppedeponte commented on agir/groups/views/public_views.py
> +    static_root = "{}/agir/front/static/front/og-image/".format(os.getcwd())
J'avais fait un commentaire sur la PR #891 avec une autre manière possible de récupérer le chemin du fichier. Il faudrait voir si ça fonctionne aussi pour ces images

2021-07-28 10:09 UTC, giuseppedeponte approved these changes

2021-07-29 13:56 UTC, giuseppedeponte approved these changes

2021-08-09 14:39 UTC, maxGoaz approved these changes

2021-08-09 22:40 UTC, jillro requested changes
Le .path ne marche pas avec le storage sur S3 que nous utilisons en production. Il faut utiliser les méthodes open de ImageField. Pour les fichiers static, le mieux est par contre de les récupérer directement sur le disque sans passer par l'URL et static_root (voir https://github.com/lafranceinsoumise/actionpopulaire.fr/commit/e6f765dff78d01e821a0a326730b4b3aa47b8f42)

Pour le resize, attention, il déforme l'image en changeant les proportions. Il faut d'abord resize à proportions constantes, puis crop pour avoir la hauteur désirée (voir https://github.com/lafranceinsoumise/actionpopulaire.fr/commit/817282f7aa5d58479dd30cc121bff57b6a388cb9)

2021-11-25 15:56 UTC, giuseppedeponte commented
Superseded by  #1266

2021-11-25 15:56 UTC, closed without merging