Fix: update old urls for new group
lafranceinsoumise/actionpopulaire.fr pull request #955
Opened 2021-09-02 12:26 UTC by maxGoaz

2021-09-02 12:33 UTC, giuseppedeponte requested changes

2021-09-02 12:33 UTC, giuseppedeponte commented on agir/events/components/createEventPage/CreateEvent.js
>        >
Ça devrait fonctionner normalement comme ça :
```
<Link route="newGroupHelp" target="_blank" rel="noopener noreferrer" />
```
sinon c'est toujours mieux d'importer la config

2021-09-02 12:33 UTC, giuseppedeponte commented on agir/groups/components/groupPage/EmptyContent.js
> -      <a href="https://infos.actionpopulaire.fr/groupes/nouvelle-equipe/">
Ça devrait fonctionner normalement comme ça :
```
<Link route="newGroupHelp" target="_blank" rel="noopener noreferrer" />
```
sinon c'est toujours mieux d'importer la config

2021-09-06 11:33 UTC, giuseppedeponte approved these changes

2021-09-08 11:28 UTC, jillro approved these changes

2021-09-08 11:28 UTC, merged