Fix: show keyboard tor responding to messages on iOS
lafranceinsoumise/actionpopulaire.fr pull request #957
Opened 2021-09-02 14:21 UTC by maxGoaz

… isFocused var

2021-09-03 09:04 UTC, jillro requested changes

2021-09-03 09:04 UTC, jillro commented on agir/front/components/formComponents/CommentField.js
> +      if (autoScroll)
C'est une convention du projet, on évite les if sans {.

2021-09-03 09:15 UTC, jillro requested changes

2021-09-03 09:15 UTC, jillro commented on agir/front/components/formComponents/CommentField.js
> +      autoScroll &&
Du coup pareil, hors rendu React c'est bien d'utiliser des vrais conditions.

2021-09-03 09:21 UTC, maxGoaz commented on agir/front/components/formComponents/CommentField.js
> +      autoScroll &&
Ah d'accord, j'avais commencé à refactor ça justement mais j'ai vu qu'il y avait plein d' `autoScroll && func()` donc j'ai remis pareil.
Je mets ça à la norme ! :)

2021-09-03 12:52 UTC, giuseppedeponte approved these changes

2021-09-08 11:34 UTC, jillro approved these changes

2021-09-08 11:34 UTC, merged