Panel event: feedbacks
lafranceinsoumise/actionpopulaire.fr pull request #989
Opened 2021-09-08 16:27 UTC by maxGoaz

Send notifications when event change
Update geolocation when location change
Show group in event organization
Fix time display from timezone

2021-09-09 15:08 UTC, giuseppedeponte requested changes

2021-09-09 15:08 UTC, giuseppedeponte commented on agir/events/components/eventPage/EventReportCard.js
> +import Spacer from "@agir/front/genericComponents/Spacer.js";
```suggestion
import Spacer from "@agir/front/genericComponents/Spacer";
```

2021-09-09 15:08 UTC, giuseppedeponte commented on agir/events/components/eventPage/EventReportCard.js
> +            routeConfig.eventSettings.getLink({ eventPk: id }) + "compte-rendu/"
```suggestion
            routeConfig.eventSettings.getLink({ eventPk: id, activePanel: "compte-rendu" })
```

2021-09-09 15:08 UTC, giuseppedeponte commented on agir/events/serializers.py
> +        return photos
```suggestion
        photos = [
            {
                "image": instance.image.url,
                "thumbnail": instance.image.thumbnail.url,
                "legend": instance.legend,
            }
            for instance in obj.images.all()
        ]
        if obj.report_image:
            photos.insert(
                0,
                {
                    "image": obj.report_image.url,
                    "thumbnail": obj.report_image.thumbnail.url,
                    "banner": obj.report_image.banner.url,
                    "isReportImage": True,
                }
            )
        return photos
```

2021-09-09 15:08 UTC, giuseppedeponte commented on agir/events/serializers.py
> +            send_event_changed_notification.delay(self.instance.pk, self.changed_data)
Ici la notification est envoyée uniquement si l'adresse a changé. Il faudrait l'envoyer aussi pour d'autre changements (cf. `agir/events/forms.py:55`)

2021-09-10 15:37 UTC, giuseppedeponte requested changes

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/events/serializers.py
> +from agir.lib.model_fields import facebookEventValidator
En python on utilise plutôt le snake case et vu que c'est une fonction ce serait plutôt `validate_facebook_event_url`.
Et vu que ce n'est plus lié à un champs de modèle c'est probablement mieux de le mettre dans `agir/lib/utils.py`

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/events/serializers.py
> +}
Il existe la même chose dans `agir/events/tasks.py:27`, on peut l'importer directement de là

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/events/serializers.py
> +            )
Une autre possibilité est aussi d'ajouter directement le validateur en argument du champs : 
```python
facebook = serializers.CharField(validators=[validate_facebook_event_url])
```
cf. https://www.django-rest-framework.org/api-guide/validators/#writing-custom-validators

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/events/serializers.py
> +                {"endTime": "L'événement ne peut pas durer plus de 7 jours."}
Une autre manière de faire, où on définit tous les messages d'erreur au même endroit :
https://www.django-rest-framework.org/api-guide/fields/#raising-validation-errors

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/events/serializers.py
> +        #     send_new_group_event_email.delay(self.organizers_groups.pk, self.instance.pk)
Pas besoin de commenter ce code, non ? 
Si on n'envoie pas `as_group` pour l'instant il ne sera juste pas executé

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/events/serializers.py
> +        event = Event.objects.get(pk=self.instance.pk)
Il y a un problème ici, c'est qu'on envoie toutes les notifications alors qu'on n'a pas encore enregistré les modifications en base de données. C'est pour ça que tu es obligé de faire une requête en BDD pour récupérer l'événement. Tout ça devrait se passer après la ligne 553 ou en plus tu auras déjà l'instance de event sans besoin de plus de requêtes.

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/lib/model_fields.py
> +)
Tu peux utiliser ce message aussi dans le serializer, non ?

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/lib/model_fields.py
> +)
Et plutôt l'appeler INVALID_FACEBOOK_EVENT_LINK_MESSAGE

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/lib/model_fields.py
> +    return False
Je crois que la convention c'est plutôt d'avoir une exception dans le validateur, plutôt que de renvoyer un boolean.
```suggestion
  raise TypeError(INVALID_FACEBOOK_EVENT_LINK_MESSAGE)
```

2021-09-10 15:37 UTC, giuseppedeponte commented on agir/lib/model_fields.py
> +        return facebook_value
ça donnerait :
```python
try:
  value = validate_facebook_event_url(value)
  return value
except TypeError as err:
  raise exceptions.ValidationError(err, params={"value": value})
```

2021-09-10 15:38 UTC, giuseppedeponte requested changes

2021-09-10 15:38 UTC, giuseppedeponte commented on agir/front/components/genericComponents/ContactCard.js
> +      {phone && !hidePhone && <IconListItem name="phone">{phone}</IconListItem>}
Normalement ça devrait se faire côté back, directement dans le serializer. Si ça ne fonctionne pas c'est un bug.

2021-09-13 13:46 UTC, maxGoaz commented on agir/events/serializers.py
> +        #     send_new_group_event_email.delay(self.organizers_groups.pk, self.instance.pk)
En l'état ça fail car organizer_config n'existe pas

2021-09-14 08:24 UTC, giuseppedeponte requested changes

2021-09-14 08:24 UTC, giuseppedeponte commented on agir/events/components/common/api.js
> +  if (!body.facebook) {
En règle générale, c'est toujours mieux d'éviter de faire de la mutation d'objets qui viennent d'autres parties du code et d'en faire uniquement si on est sûrs de ne rien casser.
Ici, par exemple, c'est mieux de faire : 
```js
const body = { ...data };
body.subtype = body?.subtype?.id || undefined;
body.facebook = body.facebook || undefined;
``` 
D'ailleurs c'est voulu qu'on ne puisse pas envoyer une chaîne vide pour la value du champs facebook ?

2021-09-14 08:24 UTC, giuseppedeponte commented on agir/events/components/createEventPage/EventForm/SubtypeField.js
> +      console.log(subtype);
```suggestion
```
(c'est moi qui ai laissé ça je crois)

2021-09-14 08:24 UTC, giuseppedeponte commented on agir/events/serializers.py
> +            return ""
Ça ne devrait pas arriver, non ? Sinon un manière plus simple de faire ça est de spécifier une valeur par défaut pour le champs
```python
facebook = serializers.CharField(default="")
```

2021-09-14 10:42 UTC, giuseppedeponte requested changes

2021-09-14 10:42 UTC, giuseppedeponte commented on agir/events/components/EventSettings/EventGeneral.js
> +    setIsLoading(false);
```suggestion
```

2021-09-14 10:42 UTC, giuseppedeponte commented on agir/events/components/EventSettings/EventGeneral.js
> +    setHasCheckedImageLicence(false);
```suggestion
```

2021-09-14 12:57 UTC, giuseppedeponte approved these changes

2021-09-14 13:02 UTC, merged